const RECIPES2 = [
  // ── Japanese ────────────────────────────────────────────────
  {
    id: 31, name: "Miso Soup", image: "🍜",
    time: { prep: 5, cook: 10, total: 15 }, servings: 4, difficulty: "Easy",
    equipment: ["Stove", "Medium Pot"],
    tags: ["Japanese", "Soup", "Quick"],
    ingredients: [
      { name: "dashi stock", amount: "1", unit: "liter" },
      { name: "miso paste", amount: "3", unit: "tbsp" },
      { name: "tofu", amount: "150", unit: "g firm" },
      { name: "dried wakame seaweed", amount: "1", unit: "tbsp" },
      { name: "spring onions", amount: "2", unit: "stalks" },
    ],
    steps: [
      "Bring dashi stock to a gentle simmer in a pot over medium heat.",
      "Dice tofu into 1cm cubes. Soak wakame in cold water for 5 minutes, then drain.",
      "Add tofu to the simmering stock and warm for 2 minutes.",
      "Remove pot from heat. Dissolve miso paste in a ladle of the hot stock, then stir back into the pot — never boil miso.",
      "Add wakame. Ladle into bowls and top with sliced spring onions.",
    ],
  },
  {
    id: 32, name: "Gyoza", image: "🥟",
    time: { prep: 30, cook: 15, total: 45 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Non-stick Pan", "Lid"],
    tags: ["Japanese", "Snack", "Dumplings"],
    ingredients: [
      { name: "gyoza wrappers", amount: "30", unit: "" },
      { name: "ground pork", amount: "300", unit: "g" },
      { name: "cabbage", amount: "150", unit: "g finely chopped" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tbsp fresh" },
      { name: "soy sauce", amount: "2", unit: "tbsp" },
      { name: "sesame oil", amount: "1", unit: "tbsp" },
      { name: "spring onions", amount: "3", unit: "stalks" },
      { name: "vegetable oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Salt the cabbage and squeeze out all excess water. Finely chop.",
      "Mix pork, cabbage, minced garlic, minced ginger, soy sauce, sesame oil, and chopped spring onions.",
      "Place 1 tsp of filling in the center of each wrapper. Wet the edges, fold in half, and pleat to seal.",
      "Heat oil in a non-stick pan over medium-high heat. Add gyoza flat-side down and fry 2 minutes until golden.",
      "Add 1/4 cup water and immediately cover. Steam for 5–6 minutes until water evaporates.",
      "Remove lid and let the bottoms crisp up for 1 more minute.",
      "Serve with soy sauce and rice vinegar for dipping.",
    ],
  },
  {
    id: 33, name: "Teriyaki Chicken", image: "🍗",
    time: { prep: 10, cook: 20, total: 30 }, servings: 3, difficulty: "Easy",
    equipment: ["Stove", "Pan"],
    tags: ["Japanese", "Dinner", "Protein"],
    ingredients: [
      { name: "chicken thighs", amount: "4", unit: "boneless" },
      { name: "soy sauce", amount: "4", unit: "tbsp" },
      { name: "mirin", amount: "3", unit: "tbsp" },
      { name: "sugar", amount: "1", unit: "tbsp" },
      { name: "sake", amount: "2", unit: "tbsp" },
      { name: "vegetable oil", amount: "1", unit: "tbsp" },
      { name: "sesame seeds", amount: "1", unit: "tsp to serve" },
    ],
    steps: [
      "Mix soy sauce, mirin, sake, and sugar in a bowl. Set aside.",
      "Pat chicken dry. Heat oil in a pan over medium-high heat.",
      "Place chicken skin-side down and cook 7 minutes until golden.",
      "Flip and cook 5 more minutes until cooked through.",
      "Pour in the teriyaki sauce. Cook 2–3 minutes, turning chicken to coat, until sauce thickens and glazes.",
      "Slice and serve over rice, topped with sesame seeds.",
    ],
  },
  {
    id: 34, name: "Shoyu Ramen", image: "🍜",
    time: { prep: 15, cook: 30, total: 45 }, servings: 2, difficulty: "Medium",
    equipment: ["Stove", "Large Pot", "Pan"],
    tags: ["Japanese", "Soup", "Noodles", "Comfort Food"],
    ingredients: [
      { name: "ramen noodles", amount: "200", unit: "g" },
      { name: "chicken broth", amount: "1", unit: "liter" },
      { name: "soy sauce", amount: "4", unit: "tbsp" },
      { name: "mirin", amount: "2", unit: "tbsp" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tbsp fresh" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "spring onions", amount: "2", unit: "stalks" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
      { name: "nori", amount: "2", unit: "sheets" },
    ],
    steps: [
      "Soft-boil eggs: simmer 7 minutes then transfer to ice water. Peel and halve.",
      "Combine broth, soy sauce, mirin, sliced ginger, and crushed garlic. Simmer 20 minutes.",
      "Strain the broth and return to pot. Add sesame oil.",
      "Cook ramen noodles according to package instructions. Drain.",
      "Divide noodles between bowls. Ladle hot broth over the top.",
      "Top with halved soft-boiled eggs, sliced spring onions, and nori sheets.",
    ],
  },
  {
    id: 35, name: "Katsu Curry", image: "🍛",
    time: { prep: 15, cook: 30, total: 45 }, servings: 2, difficulty: "Medium",
    equipment: ["Stove", "Pan", "Pot"],
    tags: ["Japanese", "Dinner", "Curry"],
    ingredients: [
      { name: "chicken breast", amount: "2", unit: "fillets" },
      { name: "eggs", amount: "1", unit: "large" },
      { name: "breadcrumbs", amount: "1", unit: "cup panko" },
      { name: "flour", amount: "4", unit: "tbsp" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "carrot", amount: "1", unit: "medium" },
      { name: "curry powder", amount: "2", unit: "tbsp" },
      { name: "vegetable oil", amount: "4", unit: "tbsp" },
      { name: "soy sauce", amount: "1", unit: "tbsp" },
      { name: "chicken broth", amount: "400", unit: "ml" },
      { name: "cornstarch", amount: "1", unit: "tbsp" },
      { name: "cooked rice", amount: "2", unit: "cups" },
    ],
    steps: [
      "Flatten chicken with a rolling pin to even thickness. Season with salt.",
      "Coat chicken in flour, then beaten egg, then panko breadcrumbs.",
      "Fry in oil over medium heat, 4–5 minutes per side until golden and cooked through. Rest on a rack.",
      "Sauté diced onion and carrot in 1 tbsp oil for 5 minutes. Add curry powder, cook 1 minute.",
      "Add broth and soy sauce. Simmer 10 minutes. Mix cornstarch with a splash of cold water and stir in to thicken.",
      "Slice chicken into strips. Serve over rice with curry sauce poured alongside.",
    ],
  },
  {
    id: 36, name: "Onigiri", image: "🍙",
    time: { prep: 15, cook: 5, total: 20 }, servings: 4, difficulty: "Easy",
    equipment: ["Stove", "Large Pot", "Mixing Bowl"],
    tags: ["Japanese", "Snack", "Lunch"],
    ingredients: [
      { name: "short-grain rice", amount: "300", unit: "g" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "canned tuna", amount: "100", unit: "g" },
      { name: "mayonnaise", amount: "2", unit: "tbsp" },
      { name: "soy sauce", amount: "1", unit: "tsp" },
      { name: "nori", amount: "4", unit: "strips" },
    ],
    steps: [
      "Cook rice and let it cool until just warm enough to handle.",
      "Mix tuna with mayonnaise and soy sauce.",
      "Wet your hands and sprinkle them with salt. Take a handful of rice and flatten it in your palm.",
      "Place a spoonful of tuna filling in the center.",
      "Fold rice around the filling and press firmly into a triangle shape.",
      "Wrap a strip of nori around the base. Serve immediately or wrap in plastic to keep.",
    ],
  },

  // ── Chinese ──────────────────────────────────────────────────
  {
    id: 37, name: "Kung Pao Chicken", image: "🍗",
    time: { prep: 15, cook: 15, total: 30 }, servings: 3, difficulty: "Medium",
    equipment: ["Stove", "Wok or Large Pan"],
    tags: ["Chinese", "Dinner", "Spicy"],
    ingredients: [
      { name: "chicken breast", amount: "400", unit: "g" },
      { name: "dried chili peppers", amount: "6", unit: "" },
      { name: "peanuts", amount: "60", unit: "g roasted" },
      { name: "soy sauce", amount: "3", unit: "tbsp" },
      { name: "rice vinegar", amount: "1", unit: "tbsp" },
      { name: "sugar", amount: "1", unit: "tsp" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tsp" },
      { name: "cornstarch", amount: "1", unit: "tsp" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
      { name: "vegetable oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Cut chicken into 2cm cubes. Toss with 1 tbsp soy sauce and cornstarch.",
      "Mix remaining soy sauce, rice vinegar, sugar, and sesame oil in a bowl. Set aside.",
      "Heat oil in a wok over high heat. Add dried chilies and stir-fry 30 seconds.",
      "Add chicken and stir-fry 5 minutes until golden.",
      "Add minced garlic and ginger, stir-fry 30 seconds.",
      "Pour in the sauce and toss to coat. Cook 2 minutes.",
      "Add peanuts and toss. Serve over steamed rice.",
    ],
  },
  {
    id: 38, name: "Sweet and Sour Pork", image: "🍖",
    time: { prep: 20, cook: 20, total: 40 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Wok or Large Pan", "Mixing Bowl"],
    tags: ["Chinese", "Dinner"],
    ingredients: [
      { name: "pork shoulder", amount: "400", unit: "g" },
      { name: "bell pepper", amount: "1", unit: "red" },
      { name: "pineapple chunks", amount: "150", unit: "g" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "eggs", amount: "1", unit: "large" },
      { name: "cornstarch", amount: "4", unit: "tbsp" },
      { name: "ketchup", amount: "3", unit: "tbsp" },
      { name: "rice vinegar", amount: "2", unit: "tbsp" },
      { name: "sugar", amount: "2", unit: "tbsp" },
      { name: "soy sauce", amount: "1", unit: "tbsp" },
      { name: "vegetable oil", amount: "1", unit: "cup for frying" },
    ],
    steps: [
      "Cut pork into bite-sized pieces. Dip in beaten egg then coat in cornstarch.",
      "Heat oil in a wok to 350°F / 175°C and deep-fry pork pieces until golden, about 5 minutes. Drain.",
      "Mix ketchup, rice vinegar, sugar, and soy sauce in a bowl.",
      "Drain most oil, leaving 1 tbsp. Stir-fry peppers and onion 3 minutes.",
      "Add pineapple and the sauce. Bring to a boil and let thicken 1 minute.",
      "Return pork to wok, toss to coat. Serve immediately over rice.",
    ],
  },
  {
    id: 39, name: "Mapo Tofu", image: "🫕",
    time: { prep: 10, cook: 20, total: 30 }, servings: 3, difficulty: "Medium",
    equipment: ["Stove", "Wok or Pan"],
    tags: ["Chinese", "Dinner", "Spicy", "Vegetarian"],
    ingredients: [
      { name: "tofu", amount: "400", unit: "g soft" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tbsp fresh" },
      { name: "chili bean paste", amount: "2", unit: "tbsp" },
      { name: "soy sauce", amount: "1", unit: "tbsp" },
      { name: "vegetable broth", amount: "1", unit: "cup" },
      { name: "cornstarch", amount: "1", unit: "tbsp" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
      { name: "spring onions", amount: "2", unit: "stalks" },
      { name: "vegetable oil", amount: "2", unit: "tbsp" },
      { name: "Sichuan peppercorns", amount: "1", unit: "tsp ground" },
    ],
    steps: [
      "Cut tofu into 2cm cubes. Gently simmer in salted water 2 minutes to firm up. Drain.",
      "Heat oil in a wok over medium heat. Add chili bean paste and cook 1 minute until fragrant and oil turns red.",
      "Add minced garlic and ginger. Cook 30 seconds.",
      "Pour in vegetable broth and soy sauce. Bring to a simmer.",
      "Gently add tofu. Simmer 5 minutes.",
      "Mix cornstarch with 2 tbsp cold water and stir in to thicken the sauce.",
      "Finish with sesame oil and Sichuan peppercorns. Garnish with spring onions.",
    ],
  },
  {
    id: 40, name: "Egg Drop Soup", image: "🍳",
    time: { prep: 5, cook: 10, total: 15 }, servings: 4, difficulty: "Easy",
    equipment: ["Stove", "Medium Pot"],
    tags: ["Chinese", "Soup", "Quick"],
    ingredients: [
      { name: "chicken broth", amount: "1", unit: "liter" },
      { name: "eggs", amount: "3", unit: "large" },
      { name: "cornstarch", amount: "2", unit: "tbsp" },
      { name: "soy sauce", amount: "1", unit: "tbsp" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
      { name: "ginger", amount: "1/2", unit: "tsp ground" },
      { name: "spring onions", amount: "2", unit: "stalks" },
      { name: "salt", amount: "1/2", unit: "tsp" },
    ],
    steps: [
      "Bring broth to a boil. Add soy sauce, ginger, and salt.",
      "Mix cornstarch with 3 tbsp cold water and stir into the boiling broth until slightly thickened.",
      "Beat eggs with a fork in a small bowl.",
      "While stirring the soup in a slow circle, pour the beaten eggs in a thin, steady stream.",
      "The eggs will cook into wispy ribbons. Remove from heat immediately.",
      "Drizzle with sesame oil. Serve topped with sliced spring onions.",
    ],
  },
  {
    id: 41, name: "Char Siu (BBQ Pork)", image: "🍖",
    time: { prep: 15, cook: 40, total: 55 }, servings: 4, difficulty: "Medium",
    temperature: { f: 425, c: 220 },
    equipment: ["Oven", "Baking Sheet", "Oven Mitts"],
    tags: ["Chinese", "Dinner", "BBQ"],
    ingredients: [
      { name: "pork shoulder", amount: "600", unit: "g" },
      { name: "soy sauce", amount: "3", unit: "tbsp" },
      { name: "honey", amount: "3", unit: "tbsp" },
      { name: "hoisin sauce", amount: "2", unit: "tbsp" },
      { name: "oyster sauce", amount: "1", unit: "tbsp" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "five-spice powder", amount: "1/2", unit: "tsp" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
      { name: "red food coloring", amount: "few drops", unit: "optional" },
    ],
    steps: [
      "Cut pork into 4cm thick strips.",
      "Mix all remaining ingredients into a marinade. Reserve 3 tbsp for glazing.",
      "Marinate pork at least 4 hours or overnight in the fridge.",
      "Preheat oven to 425°F / 220°C. Place pork on a wire rack over a foil-lined baking sheet.",
      "Roast 20 minutes. Flip, brush with reserved glaze, and roast another 15–20 minutes until caramelized.",
      "Broil for the final 2–3 minutes for extra char. Rest 5 minutes before slicing.",
    ],
  },
  {
    id: 42, name: "Wonton Soup", image: "🥟",
    time: { prep: 30, cook: 15, total: 45 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Large Pot", "Mixing Bowl"],
    tags: ["Chinese", "Soup", "Dumplings"],
    ingredients: [
      { name: "wonton wrappers", amount: "30", unit: "" },
      { name: "ground pork", amount: "250", unit: "g" },
      { name: "shrimp", amount: "100", unit: "g chopped" },
      { name: "soy sauce", amount: "2", unit: "tbsp" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
      { name: "ginger", amount: "1", unit: "tsp fresh" },
      { name: "chicken broth", amount: "1.2", unit: "liters" },
      { name: "spring onions", amount: "3", unit: "stalks" },
      { name: "bok choy", amount: "2", unit: "heads" },
    ],
    steps: [
      "Mix pork, shrimp, 1 tbsp soy sauce, sesame oil, and ginger.",
      "Place 1 tsp filling in each wonton wrapper. Wet edges and fold into triangles, then pull corners together.",
      "Bring broth to a simmer with remaining soy sauce.",
      "Boil wontons in a separate pot of water for 4–5 minutes until they float and are cooked through.",
      "Add bok choy to the broth and simmer 2 minutes.",
      "Divide wontons and bok choy into bowls, ladle hot broth over top, and garnish with spring onions.",
    ],
  },

  // ── Thai ────────────────────────────────────────────────────
  {
    id: 43, name: "Pad Thai", image: "🍜",
    time: { prep: 15, cook: 15, total: 30 }, servings: 2, difficulty: "Medium",
    equipment: ["Stove", "Wok or Large Pan"],
    tags: ["Thai", "Noodles", "Dinner"],
    ingredients: [
      { name: "rice noodles", amount: "200", unit: "g flat" },
      { name: "shrimp", amount: "200", unit: "g peeled" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "bean sprouts", amount: "1", unit: "cup" },
      { name: "spring onions", amount: "3", unit: "stalks" },
      { name: "peanuts", amount: "40", unit: "g crushed" },
      { name: "fish sauce", amount: "2", unit: "tbsp" },
      { name: "tamarind paste", amount: "2", unit: "tbsp" },
      { name: "sugar", amount: "1", unit: "tbsp" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "vegetable oil", amount: "3", unit: "tbsp" },
      { name: "lime", amount: "1", unit: "to serve" },
    ],
    steps: [
      "Soak rice noodles in warm water 30 minutes until pliable. Drain.",
      "Mix fish sauce, tamarind paste, and sugar. Set aside.",
      "Heat oil in a wok over high heat. Add minced garlic and shrimp. Cook 2 minutes.",
      "Push to the side. Crack eggs into the wok and scramble.",
      "Add noodles and pour sauce over. Toss everything together over high heat 2 minutes.",
      "Add bean sprouts and spring onions. Toss 30 seconds — keep the sprouts crunchy.",
      "Serve topped with crushed peanuts and a lime wedge.",
    ],
  },
  {
    id: 44, name: "Thai Green Curry", image: "🍛",
    time: { prep: 10, cook: 25, total: 35 }, servings: 4, difficulty: "Easy",
    equipment: ["Stove", "Large Pan or Wok"],
    tags: ["Thai", "Dinner", "Curry", "Spicy"],
    ingredients: [
      { name: "chicken breast", amount: "400", unit: "g" },
      { name: "coconut milk", amount: "400", unit: "ml" },
      { name: "green curry paste", amount: "3", unit: "tbsp" },
      { name: "fish sauce", amount: "2", unit: "tbsp" },
      { name: "sugar", amount: "1", unit: "tsp" },
      { name: "zucchini", amount: "1", unit: "medium" },
      { name: "bell pepper", amount: "1", unit: "green" },
      { name: "fresh basil", amount: "handful", unit: "Thai basil" },
      { name: "vegetable oil", amount: "1", unit: "tbsp" },
      { name: "lime", amount: "1", unit: "" },
    ],
    steps: [
      "Slice chicken into strips. Slice zucchini and pepper.",
      "Heat oil in a pan over medium heat. Add green curry paste and fry 1 minute until fragrant.",
      "Add half the coconut milk. Stir until it bubbles and thickens slightly.",
      "Add chicken and cook 5 minutes.",
      "Pour in remaining coconut milk, fish sauce, and sugar.",
      "Add vegetables and simmer 10 minutes until chicken is cooked and vegetables tender.",
      "Stir in basil leaves. Squeeze lime juice over top. Serve with jasmine rice.",
    ],
  },
  {
    id: 45, name: "Tom Yum Soup", image: "🍲",
    time: { prep: 10, cook: 20, total: 30 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Large Pot"],
    tags: ["Thai", "Soup", "Spicy"],
    ingredients: [
      { name: "shrimp", amount: "300", unit: "g peeled" },
      { name: "mushrooms", amount: "150", unit: "g" },
      { name: "lemongrass", amount: "2", unit: "stalks" },
      { name: "galangal or ginger", amount: "3", unit: "slices" },
      { name: "kaffir lime leaves", amount: "4", unit: "" },
      { name: "chili peppers", amount: "3", unit: "Thai" },
      { name: "fish sauce", amount: "3", unit: "tbsp" },
      { name: "lime", amount: "2", unit: "" },
      { name: "sugar", amount: "1", unit: "tsp" },
      { name: "chicken broth", amount: "1", unit: "liter" },
      { name: "fresh cilantro", amount: "handful", unit: "" },
    ],
    steps: [
      "Smash lemongrass with the back of a knife and cut into 5cm pieces.",
      "Bring broth to a boil. Add lemongrass, galangal, lime leaves, and chilies. Simmer 5 minutes.",
      "Add mushrooms and cook 3 minutes.",
      "Add shrimp and cook 2–3 minutes until pink.",
      "Season with fish sauce, lime juice, and sugar.",
      "Taste — it should be sour, spicy, and salty in balance. Adjust as needed.",
      "Garnish with fresh cilantro. Remove lemongrass and galangal before eating.",
    ],
  },
  {
    id: 46, name: "Mango Sticky Rice", image: "🥭",
    time: { prep: 10, cook: 30, total: 40 }, servings: 4, difficulty: "Easy",
    equipment: ["Stove", "Medium Pot"],
    tags: ["Thai", "Dessert", "Sweet"],
    ingredients: [
      { name: "glutinous rice", amount: "300", unit: "g" },
      { name: "coconut milk", amount: "400", unit: "ml" },
      { name: "sugar", amount: "80", unit: "g" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "mango", amount: "2", unit: "ripe" },
      { name: "sesame seeds", amount: "1", unit: "tsp to serve" },
    ],
    steps: [
      "Soak glutinous rice in water for at least 1 hour. Drain.",
      "Steam rice over boiling water for 20–25 minutes until fully cooked and sticky.",
      "Heat coconut milk with sugar and salt until sugar dissolves — do not boil.",
      "Pour 2/3 of the coconut sauce over the hot rice. Stir gently and let absorb 10 minutes.",
      "Peel and slice mangoes.",
      "Serve rice in mounds alongside sliced mango. Drizzle remaining coconut sauce over rice and sprinkle with sesame seeds.",
    ],
  },
  {
    id: 47, name: "Som Tum (Green Papaya Salad)", image: "🥗",
    time: { prep: 20, cook: 0, total: 20 }, servings: 2, difficulty: "Medium",
    equipment: ["Mortar and Pestle or Large Bowl", "Knife"],
    tags: ["Thai", "Salad", "No-Cook", "Spicy"],
    ingredients: [
      { name: "green papaya", amount: "300", unit: "g shredded" },
      { name: "cherry tomatoes", amount: "8", unit: "" },
      { name: "green beans", amount: "8", unit: "" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "chili peppers", amount: "2", unit: "Thai" },
      { name: "peanuts", amount: "30", unit: "g roasted" },
      { name: "fish sauce", amount: "2", unit: "tbsp" },
      { name: "lime", amount: "1", unit: "" },
      { name: "sugar", amount: "1", unit: "tbsp" },
    ],
    steps: [
      "Pound garlic and chilies in a mortar to a rough paste.",
      "Add green beans and lightly bruise them.",
      "Add tomatoes and gently pound to release juices.",
      "Add shredded papaya, fish sauce, lime juice, and sugar. Toss and lightly pound to combine.",
      "Taste — adjust fish sauce (salty), lime (sour), and sugar (sweet).",
      "Top with crushed peanuts. Serve immediately.",
    ],
  },

  // ── Vietnamese ───────────────────────────────────────────────
  {
    id: 48, name: "Phở Bò", image: "🍜",
    time: { prep: 20, cook: 60, total: 80 }, servings: 4, difficulty: "Hard",
    equipment: ["Stove", "Large Pot", "Strainer"],
    tags: ["Vietnamese", "Soup", "Noodles"],
    ingredients: [
      { name: "beef broth", amount: "2", unit: "liters" },
      { name: "beef sirloin", amount: "300", unit: "g thinly sliced" },
      { name: "rice noodles", amount: "400", unit: "g flat" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "ginger", amount: "50", unit: "g" },
      { name: "star anise", amount: "3", unit: "" },
      { name: "cinnamon stick", amount: "1", unit: "" },
      { name: "fish sauce", amount: "3", unit: "tbsp" },
      { name: "sugar", amount: "1", unit: "tsp" },
      { name: "bean sprouts", amount: "150", unit: "g" },
      { name: "fresh basil", amount: "handful", unit: "Thai" },
      { name: "lime", amount: "1", unit: "" },
      { name: "spring onions", amount: "3", unit: "stalks" },
    ],
    steps: [
      "Char the onion and ginger directly over a flame or under a broiler until blackened on the outside. Rinse.",
      "Toast star anise and cinnamon stick in a dry pot 1 minute. Add broth, charred onion and ginger.",
      "Simmer broth 40 minutes. Strain and season with fish sauce and sugar.",
      "Cook rice noodles per package instructions. Drain and divide into bowls.",
      "Ladle very hot broth over noodles — the heat will cook the thinly sliced raw beef.",
      "Top with raw beef slices, bean sprouts, basil, spring onions, and lime wedge.",
    ],
  },
  {
    id: 49, name: "Fresh Spring Rolls", image: "🫔",
    time: { prep: 25, cook: 10, total: 35 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Pan", "Large Bowl of Warm Water"],
    tags: ["Vietnamese", "Snack", "Healthy", "No-Cook"],
    ingredients: [
      { name: "rice paper wrappers", amount: "12", unit: "" },
      { name: "shrimp", amount: "200", unit: "g cooked" },
      { name: "rice vermicelli", amount: "100", unit: "g" },
      { name: "lettuce", amount: "6", unit: "leaves" },
      { name: "cucumber", amount: "1/2", unit: "" },
      { name: "carrot", amount: "1", unit: "medium" },
      { name: "fresh mint", amount: "handful", unit: "" },
      { name: "fresh cilantro", amount: "handful", unit: "" },
      { name: "peanut butter", amount: "3", unit: "tbsp" },
      { name: "hoisin sauce", amount: "2", unit: "tbsp" },
      { name: "lime", amount: "1", unit: "" },
    ],
    steps: [
      "Cook vermicelli per package instructions. Drain and rinse with cold water.",
      "Julienne carrot and cucumber into thin sticks. Halve shrimp lengthwise.",
      "Make dipping sauce: mix peanut butter, hoisin sauce, lime juice, and a splash of water until smooth.",
      "Briefly dip a rice paper wrapper in warm water for 10 seconds until just pliable.",
      "Lay flat on a board. Place shrimp, then lettuce, vermicelli, vegetables, and herbs on the lower third.",
      "Fold sides in and roll tightly from the bottom up. Repeat.",
      "Serve immediately with peanut dipping sauce.",
    ],
  },
  {
    id: 50, name: "Bánh Mì", image: "🥖",
    time: { prep: 20, cook: 10, total: 30 }, servings: 2, difficulty: "Easy",
    equipment: ["Oven or Toaster", "Knife", "Mixing Bowl"],
    tags: ["Vietnamese", "Sandwich", "Lunch"],
    ingredients: [
      { name: "baguette", amount: "1", unit: "fresh" },
      { name: "pork belly", amount: "200", unit: "g thin slices" },
      { name: "mayonnaise", amount: "2", unit: "tbsp" },
      { name: "carrot", amount: "1", unit: "medium" },
      { name: "daikon radish", amount: "100", unit: "g" },
      { name: "rice vinegar", amount: "3", unit: "tbsp" },
      { name: "sugar", amount: "1", unit: "tbsp" },
      { name: "cucumber", amount: "1/2", unit: "" },
      { name: "fresh cilantro", amount: "handful", unit: "" },
      { name: "jalapeño", amount: "1", unit: "sliced" },
      { name: "soy sauce", amount: "1", unit: "tbsp" },
    ],
    steps: [
      "Quick-pickle carrot and daikon: julienne finely, toss with rice vinegar, sugar, and a pinch of salt. Let sit 15 minutes.",
      "Marinate pork in soy sauce 5 minutes. Pan-fry over high heat 2–3 minutes per side.",
      "Split baguette lengthwise. Toast lightly.",
      "Spread mayonnaise on both sides.",
      "Fill with pork, pickled vegetables, cucumber slices, cilantro, and jalapeño.",
      "Serve immediately.",
    ],
  },

  // ── Korean ───────────────────────────────────────────────────
  {
    id: 51, name: "Bibimbap", image: "🍚",
    time: { prep: 20, cook: 20, total: 40 }, servings: 2, difficulty: "Medium",
    equipment: ["Stove", "Pan", "Bowls"],
    tags: ["Korean", "Dinner", "Rice Bowl"],
    ingredients: [
      { name: "cooked rice", amount: "2", unit: "cups" },
      { name: "beef mince", amount: "150", unit: "g" },
      { name: "spinach", amount: "100", unit: "g" },
      { name: "carrot", amount: "1", unit: "medium" },
      { name: "zucchini", amount: "1", unit: "small" },
      { name: "bean sprouts", amount: "100", unit: "g" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "gochujang", amount: "2", unit: "tbsp" },
      { name: "soy sauce", amount: "2", unit: "tbsp" },
      { name: "sesame oil", amount: "2", unit: "tsp" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "sesame seeds", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Marinate beef in 1 tbsp soy sauce, minced garlic, and 1 tsp sesame oil. Brown in a pan.",
      "Blanch spinach 30 seconds, squeeze dry, season with soy sauce and sesame oil.",
      "Julienne and sauté carrot and zucchini separately in a little oil until just tender.",
      "Blanch bean sprouts 1 minute, drain, season with sesame oil.",
      "Fry eggs sunny-side up.",
      "Place warm rice in bowls. Arrange each vegetable and the beef in separate sections around the bowl.",
      "Place egg on top. Add gochujang. Mix everything together before eating.",
    ],
  },
  {
    id: 52, name: "Bulgogi", image: "🥩",
    time: { prep: 15, cook: 10, total: 25 }, servings: 3, difficulty: "Easy",
    equipment: ["Stove", "Grill Pan or Pan"],
    tags: ["Korean", "Dinner", "BBQ", "Protein"],
    ingredients: [
      { name: "beef sirloin", amount: "500", unit: "g thinly sliced" },
      { name: "soy sauce", amount: "4", unit: "tbsp" },
      { name: "sugar", amount: "2", unit: "tbsp" },
      { name: "sesame oil", amount: "2", unit: "tbsp" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tsp fresh" },
      { name: "pear or apple", amount: "1/4", unit: "grated" },
      { name: "sesame seeds", amount: "1", unit: "tsp" },
      { name: "spring onions", amount: "3", unit: "stalks" },
    ],
    steps: [
      "Mix soy sauce, sugar, sesame oil, minced garlic, ginger, and grated pear into a marinade.",
      "Toss beef slices in marinade and let sit at least 30 minutes (overnight is better).",
      "Heat a grill pan or pan over high heat until very hot.",
      "Cook beef in batches — do not overcrowd — for 1–2 minutes per side.",
      "Garnish with sesame seeds and sliced spring onions.",
      "Serve with steamed rice and lettuce leaves for wrapping.",
    ],
  },
  {
    id: 53, name: "Tteokbokki", image: "🍢",
    time: { prep: 5, cook: 20, total: 25 }, servings: 2, difficulty: "Easy",
    equipment: ["Stove", "Wide Pan"],
    tags: ["Korean", "Snack", "Spicy", "Street Food"],
    ingredients: [
      { name: "rice cakes", amount: "300", unit: "g tteok" },
      { name: "fish cakes", amount: "100", unit: "g" },
      { name: "gochujang", amount: "3", unit: "tbsp" },
      { name: "soy sauce", amount: "1", unit: "tbsp" },
      { name: "sugar", amount: "1", unit: "tbsp" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "spring onions", amount: "2", unit: "stalks" },
      { name: "water", amount: "300", unit: "ml" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Soak rice cakes in cold water for 10 minutes if hard. Drain.",
      "Mix gochujang, soy sauce, sugar, and minced garlic in the water.",
      "Bring the sauce to a boil in a wide pan. Add rice cakes and fish cakes.",
      "Simmer on medium heat for 10–15 minutes, stirring frequently, until sauce thickens and rice cakes are soft.",
      "Drizzle with sesame oil and top with sliced spring onions.",
    ],
  },
  {
    id: 54, name: "Kimchi Jjigae", image: "🫕",
    time: { prep: 10, cook: 30, total: 40 }, servings: 3, difficulty: "Easy",
    equipment: ["Stove", "Medium Pot"],
    tags: ["Korean", "Soup", "Dinner", "Spicy"],
    ingredients: [
      { name: "kimchi", amount: "300", unit: "g well-fermented" },
      { name: "pork belly", amount: "200", unit: "g" },
      { name: "tofu", amount: "200", unit: "g firm" },
      { name: "onion", amount: "1/2", unit: "" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "gochujang", amount: "1", unit: "tbsp" },
      { name: "soy sauce", amount: "1", unit: "tbsp" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
      { name: "water", amount: "500", unit: "ml" },
      { name: "spring onions", amount: "2", unit: "stalks" },
    ],
    steps: [
      "Cut pork belly into bite-sized pieces. Slice onion and cube tofu.",
      "Sauté pork in a pot over medium heat for 3 minutes until lightly browned.",
      "Add minced garlic and gochujang, stir 30 seconds.",
      "Add kimchi (including its juice) and stir-fry for 3 minutes.",
      "Add water and soy sauce. Bring to a boil, then simmer 20 minutes.",
      "Add tofu and simmer 5 more minutes.",
      "Drizzle with sesame oil and top with spring onions. Serve with steamed rice.",
    ],
  },

  // ── Indian ───────────────────────────────────────────────────
  {
    id: 55, name: "Butter Chicken", image: "🍛",
    time: { prep: 20, cook: 40, total: 60 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Large Pan", "Blender"],
    tags: ["Indian", "Dinner", "Curry", "Comfort Food"],
    ingredients: [
      { name: "chicken breast", amount: "600", unit: "g" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "garlic", amount: "5", unit: "cloves" },
      { name: "ginger", amount: "2", unit: "tbsp fresh" },
      { name: "butter", amount: "3", unit: "tbsp" },
      { name: "heavy cream", amount: "150", unit: "ml" },
      { name: "yogurt", amount: "3", unit: "tbsp" },
      { name: "garam masala", amount: "2", unit: "tsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "paprika", amount: "1", unit: "tsp" },
      { name: "turmeric", amount: "1/2", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Marinate chicken in yogurt, 1 tsp garam masala, paprika, and salt for 30 minutes. Grill or pan-fry until slightly charred. Set aside.",
      "Melt butter in a large pan. Sauté diced onion 7 minutes until golden.",
      "Add garlic and ginger paste. Cook 2 minutes.",
      "Add canned tomatoes, remaining garam masala, cumin, and turmeric. Simmer 15 minutes.",
      "Blend the sauce until smooth. Return to the pan.",
      "Add the cooked chicken pieces and cream. Simmer 10 minutes.",
      "Adjust seasoning. Serve with naan or basmati rice, garnished with cream.",
    ],
  },
  {
    id: 56, name: "Dal Tadka", image: "🍲",
    time: { prep: 10, cook: 35, total: 45 }, servings: 4, difficulty: "Easy",
    equipment: ["Stove", "Medium Pot", "Small Pan"],
    tags: ["Indian", "Dinner", "Vegetarian", "Healthy"],
    ingredients: [
      { name: "red lentils", amount: "200", unit: "g" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "tomatoes", amount: "2", unit: "medium" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tbsp fresh" },
      { name: "butter", amount: "2", unit: "tbsp" },
      { name: "cumin", amount: "1", unit: "tsp seeds" },
      { name: "turmeric", amount: "1/2", unit: "tsp" },
      { name: "chili powder", amount: "1/2", unit: "tsp" },
      { name: "garam masala", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "fresh cilantro", amount: "handful", unit: "" },
    ],
    steps: [
      "Rinse lentils. Boil with 700ml water, turmeric, and salt for 20–25 minutes until very soft. Mash lightly.",
      "Finely dice onion and tomatoes. Mince garlic and ginger.",
      "Heat butter in a pan. Add cumin seeds — they should sizzle immediately.",
      "Add onion and cook 5 minutes until golden. Add garlic and ginger, cook 2 minutes.",
      "Add tomatoes, chili powder, and garam masala. Cook until tomatoes break down, 5 minutes.",
      "Pour the tadka (tempered spice mix) into the lentils and stir well. Simmer 5 minutes.",
      "Garnish with cilantro. Serve with basmati rice or naan.",
    ],
  },
  {
    id: 57, name: "Chicken Biryani", image: "🍚",
    time: { prep: 30, cook: 60, total: 90 }, servings: 4, difficulty: "Hard",
    equipment: ["Stove", "Large Pot with Lid"],
    tags: ["Indian", "Dinner", "Rice", "Celebration"],
    ingredients: [
      { name: "basmati rice", amount: "300", unit: "g" },
      { name: "chicken thighs", amount: "600", unit: "g" },
      { name: "yogurt", amount: "150", unit: "ml" },
      { name: "onion", amount: "2", unit: "large" },
      { name: "garlic", amount: "5", unit: "cloves" },
      { name: "ginger", amount: "2", unit: "tbsp fresh" },
      { name: "garam masala", amount: "2", unit: "tsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "turmeric", amount: "1/2", unit: "tsp" },
      { name: "saffron", amount: "pinch", unit: "" },
      { name: "butter", amount: "3", unit: "tbsp" },
      { name: "fresh mint", amount: "handful", unit: "" },
      { name: "salt", amount: "1.5", unit: "tsp" },
    ],
    steps: [
      "Marinate chicken with yogurt, garlic-ginger paste, garam masala, cumin, turmeric, and salt for 1 hour.",
      "Fry thinly sliced onions in butter until deeply golden and crispy. Remove half for garnish.",
      "Add marinated chicken to remaining onions. Cook 10 minutes over medium heat.",
      "Parboil basmati rice in salted water until 70% cooked (still has a bite). Drain.",
      "Steep saffron in 3 tbsp warm milk.",
      "Layer half the rice over the chicken. Scatter mint and half the crispy onions. Add remaining rice. Drizzle saffron milk on top.",
      "Seal the pot tightly (use foil then the lid). Cook on the lowest heat for 25–30 minutes. Do not open during cooking. Gently mix before serving.",
    ],
  },
  {
    id: 58, name: "Palak Paneer", image: "🥬",
    time: { prep: 15, cook: 30, total: 45 }, servings: 3, difficulty: "Medium",
    equipment: ["Stove", "Pot", "Blender"],
    tags: ["Indian", "Dinner", "Vegetarian"],
    ingredients: [
      { name: "spinach", amount: "500", unit: "g fresh" },
      { name: "paneer", amount: "250", unit: "g" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "tomatoes", amount: "2", unit: "medium" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tbsp fresh" },
      { name: "heavy cream", amount: "3", unit: "tbsp" },
      { name: "butter", amount: "2", unit: "tbsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "garam masala", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Blanch spinach in boiling water 1 minute, then transfer to ice water. Drain and blend smooth.",
      "Cut paneer into cubes. Pan-fry in a little butter until golden on all sides. Set aside.",
      "Heat butter, add cumin seeds. Add diced onion and cook 6 minutes until golden.",
      "Add garlic-ginger paste, cook 2 minutes. Add chopped tomatoes, garam masala, and salt. Cook 8 minutes.",
      "Add blended spinach. Stir and simmer 5 minutes.",
      "Add paneer and cream. Simmer 5 more minutes.",
      "Serve with naan or basmati rice.",
    ],
  },
  {
    id: 59, name: "Samosas", image: "🥟",
    time: { prep: 30, cook: 30, total: 60 }, servings: 4, difficulty: "Hard",
    equipment: ["Stove", "Pan", "Deep Fryer or Large Pot"],
    tags: ["Indian", "Snack", "Street Food", "Vegetarian"],
    ingredients: [
      { name: "flour", amount: "200", unit: "g" },
      { name: "potatoes", amount: "400", unit: "g boiled" },
      { name: "frozen peas", amount: "100", unit: "g" },
      { name: "butter", amount: "2", unit: "tbsp" },
      { name: "cumin", amount: "1", unit: "tsp seeds" },
      { name: "garam masala", amount: "1", unit: "tsp" },
      { name: "chili powder", amount: "1/2", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "vegetable oil", amount: "1", unit: "cup for frying" },
      { name: "water", amount: "4", unit: "tbsp cold" },
    ],
    steps: [
      "Make dough: rub 2 tbsp butter into flour with salt until breadcrumb texture. Add water and knead to a firm dough. Rest 30 minutes.",
      "Mash boiled potatoes. Cook cumin seeds in 1 tbsp oil, add potatoes, peas, garam masala, chili powder, and salt. Mix and cool.",
      "Divide dough into balls. Roll each into an oval, cut in half. Form each half into a cone.",
      "Fill each cone with potato mixture and seal the edges firmly with a little water.",
      "Heat oil to 350°F / 175°C. Fry samosas in batches for 4–5 minutes until golden and crispy.",
      "Drain on paper towels. Serve with mint chutney.",
    ],
  },

  // ── Moroccan ─────────────────────────────────────────────────
  {
    id: 60, name: "Chicken Tagine", image: "🍲",
    time: { prep: 15, cook: 60, total: 75 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Tagine or Heavy Pot with Lid"],
    tags: ["Moroccan", "Dinner", "African"],
    ingredients: [
      { name: "chicken thighs", amount: "6", unit: "bone-in" },
      { name: "onion", amount: "2", unit: "large" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "canned tomatoes", amount: "200", unit: "g" },
      { name: "green olives", amount: "80", unit: "g" },
      { name: "preserved lemon", amount: "1", unit: "" },
      { name: "chicken broth", amount: "300", unit: "ml" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "paprika", amount: "1", unit: "tsp" },
      { name: "turmeric", amount: "1/2", unit: "tsp" },
      { name: "cinnamon", amount: "1/4", unit: "tsp" },
      { name: "ginger", amount: "1", unit: "tsp ground" },
      { name: "fresh cilantro", amount: "handful", unit: "" },
    ],
    steps: [
      "Season chicken with cumin, paprika, turmeric, cinnamon, ginger, and salt.",
      "Heat oil in a tagine or heavy pot. Brown chicken on all sides, about 5 minutes. Remove.",
      "Sauté sliced onions 7 minutes until soft. Add garlic and cook 1 minute.",
      "Return chicken. Add tomatoes, broth, olives, and the rind of the preserved lemon (discard flesh).",
      "Cover and simmer on low heat for 45–50 minutes until chicken is very tender.",
      "Garnish with cilantro and serve with couscous or flatbread.",
    ],
  },
  {
    id: 61, name: "Harira Soup", image: "🍲",
    time: { prep: 15, cook: 60, total: 75 }, servings: 6, difficulty: "Medium",
    equipment: ["Stove", "Large Pot"],
    tags: ["Moroccan", "Soup", "African"],
    ingredients: [
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "canned chickpeas", amount: "400", unit: "g" },
      { name: "red lentils", amount: "100", unit: "g" },
      { name: "lamb mince", amount: "200", unit: "g" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "celery", amount: "2", unit: "stalks" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "tomato paste", amount: "2", unit: "tbsp" },
      { name: "vegetable broth", amount: "1.5", unit: "liters" },
      { name: "flour", amount: "2", unit: "tbsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "turmeric", amount: "1/2", unit: "tsp" },
      { name: "cinnamon", amount: "1/2", unit: "tsp" },
      { name: "fresh cilantro", amount: "handful", unit: "" },
      { name: "lemon", amount: "1", unit: "" },
    ],
    steps: [
      "Brown lamb mince in a large pot over high heat. Remove.",
      "Sauté diced onion and celery in the same pot for 5 minutes.",
      "Return lamb. Add canned tomatoes, tomato paste, broth, lentils, and all spices.",
      "Bring to a boil, then simmer 30 minutes.",
      "Add drained chickpeas. Mix flour with a cup of cold water until smooth, then stir into soup.",
      "Simmer another 15 minutes until thickened.",
      "Finish with lemon juice and cilantro. Serve with crusty bread.",
    ],
  },
  {
    id: 62, name: "Vegetable Couscous", image: "🍚",
    time: { prep: 15, cook: 30, total: 45 }, servings: 4, difficulty: "Easy",
    equipment: ["Stove", "Large Pot", "Mixing Bowl"],
    tags: ["Moroccan", "Dinner", "Vegetarian", "African"],
    ingredients: [
      { name: "couscous", amount: "300", unit: "g" },
      { name: "carrot", amount: "2", unit: "medium" },
      { name: "zucchini", amount: "2", unit: "medium" },
      { name: "bell pepper", amount: "1", unit: "red" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "canned chickpeas", amount: "400", unit: "g" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "vegetable broth", amount: "600", unit: "ml" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "paprika", amount: "1", unit: "tsp" },
      { name: "turmeric", amount: "1/2", unit: "tsp" },
      { name: "cinnamon", amount: "1/4", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Heat oil in a large pot. Sauté diced onion and carrots 5 minutes.",
      "Add cumin, paprika, turmeric, and cinnamon. Stir 1 minute.",
      "Add zucchini, pepper, canned tomatoes, chickpeas, and broth. Season with salt.",
      "Bring to a boil, simmer 20 minutes until vegetables are tender.",
      "Place couscous in a bowl. Pour 300ml of the hot broth over it. Cover and let steam 5 minutes. Fluff with a fork and add 1 tbsp olive oil.",
      "Serve couscous topped with the vegetable stew.",
    ],
  },

  // ── Lebanese / Middle Eastern ────────────────────────────────
  {
    id: 63, name: "Hummus", image: "🫘",
    time: { prep: 10, cook: 0, total: 10 }, servings: 6, difficulty: "Easy",
    equipment: ["Blender or Food Processor"],
    tags: ["Lebanese", "Dip", "Vegetarian", "No-Cook", "Middle Eastern"],
    ingredients: [
      { name: "canned chickpeas", amount: "400", unit: "g" },
      { name: "tahini", amount: "4", unit: "tbsp" },
      { name: "lemon", amount: "1", unit: "large" },
      { name: "garlic", amount: "1", unit: "clove" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "cumin", amount: "1/2", unit: "tsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "ice water", amount: "3", unit: "tbsp" },
      { name: "paprika", amount: "pinch", unit: "to serve" },
    ],
    steps: [
      "Drain chickpeas, reserving the liquid. Peel off any skins for extra smoothness.",
      "Blend tahini, lemon juice, garlic, and salt until creamy.",
      "Add chickpeas and blend. With the motor running, drizzle in ice water. Blend 3–4 minutes until very smooth.",
      "Add cumin and blend again. Adjust lemon and salt.",
      "Spread into a bowl, creating a well in the center. Drizzle with olive oil and sprinkle with paprika.",
      "Serve with warm pita bread.",
    ],
  },
  {
    id: 64, name: "Falafel", image: "🧆",
    time: { prep: 15, cook: 15, total: 30 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Food Processor or Blender", "Deep Pan"],
    tags: ["Lebanese", "Snack", "Vegetarian", "Middle Eastern", "Street Food"],
    ingredients: [
      { name: "dried chickpeas", amount: "250", unit: "g soaked overnight" },
      { name: "onion", amount: "1/2", unit: "" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "fresh parsley", amount: "large handful", unit: "" },
      { name: "fresh cilantro", amount: "large handful", unit: "" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "coriander", amount: "1", unit: "tsp ground" },
      { name: "baking powder", amount: "1/2", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "vegetable oil", amount: "1", unit: "cup for frying" },
    ],
    steps: [
      "Do not use canned chickpeas — they make falafel that falls apart. Use soaked dried ones.",
      "Blend chickpeas, onion, garlic, herbs, cumin, coriander, and salt until a coarse paste — not smooth.",
      "Mix in baking powder. Refrigerate 30 minutes.",
      "Form into small balls or patties. If mixture is too loose, add 1–2 tbsp flour.",
      "Heat oil to 350°F / 175°C. Fry falafel in batches for 3–4 minutes until deep golden and crispy.",
      "Drain and serve in pita with hummus, tomatoes, and tahini sauce.",
    ],
  },
  {
    id: 65, name: "Tabbouleh", image: "🌿",
    time: { prep: 20, cook: 10, total: 30 }, servings: 4, difficulty: "Easy",
    equipment: ["Knife", "Mixing Bowl"],
    tags: ["Lebanese", "Salad", "Vegetarian", "No-Cook", "Middle Eastern"],
    ingredients: [
      { name: "bulgur wheat", amount: "80", unit: "g" },
      { name: "fresh parsley", amount: "200", unit: "g" },
      { name: "fresh mint", amount: "30", unit: "g" },
      { name: "tomatoes", amount: "3", unit: "medium" },
      { name: "spring onions", amount: "4", unit: "stalks" },
      { name: "olive oil", amount: "4", unit: "tbsp" },
      { name: "lemon", amount: "2", unit: "" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Pour boiling water over bulgur (just enough to cover). Cover and let soak 10 minutes until tender. Drain any excess and spread to cool.",
      "Finely chop all the parsley and mint — tabbouleh is mostly herbs, not grain.",
      "Dice tomatoes and slice spring onions.",
      "Combine everything in a bowl. Dress with olive oil, lemon juice, and salt.",
      "Toss and taste — it should be bright and lemony. Adjust seasoning.",
      "Chill for 30 minutes before serving for best flavor.",
    ],
  },
  {
    id: 66, name: "Chicken Shawarma", image: "🌯",
    time: { prep: 15, cook: 25, total: 40 }, servings: 4, difficulty: "Medium",
    equipment: ["Oven", "Baking Sheet", "Oven Mitts"],
    temperature: { f: 425, c: 220 },
    tags: ["Lebanese", "Dinner", "Middle Eastern", "Street Food"],
    ingredients: [
      { name: "chicken thighs", amount: "600", unit: "g boneless" },
      { name: "yogurt", amount: "3", unit: "tbsp" },
      { name: "lemon", amount: "1", unit: "" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "paprika", amount: "1", unit: "tsp" },
      { name: "turmeric", amount: "1/2", unit: "tsp" },
      { name: "cinnamon", amount: "1/4", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "flatbread or pita", amount: "4", unit: "" },
      { name: "tomatoes", amount: "2", unit: "" },
      { name: "cucumber", amount: "1", unit: "" },
    ],
    steps: [
      "Mix yogurt, lemon juice, minced garlic, olive oil, and all spices into a marinade.",
      "Coat chicken thighs in marinade. Marinate at least 1 hour, ideally overnight.",
      "Preheat oven to 425°F / 220°C. Spread chicken on a baking sheet.",
      "Roast 20–25 minutes until slightly charred at the edges and cooked through.",
      "Slice chicken into thin strips.",
      "Serve in flatbread with sliced tomatoes, cucumber, and garlic sauce or hummus.",
    ],
  },

  // ── French ───────────────────────────────────────────────────
  {
    id: 67, name: "French Onion Soup", image: "🍲",
    time: { prep: 10, cook: 70, total: 80 }, servings: 4, difficulty: "Medium",
    temperature: { f: 400, c: 200 },
    equipment: ["Stove", "Oven", "Large Pot", "Oven-safe Bowls"],
    tags: ["French", "Soup", "Comfort Food"],
    ingredients: [
      { name: "onion", amount: "6", unit: "large" },
      { name: "butter", amount: "4", unit: "tbsp" },
      { name: "beef broth", amount: "1.2", unit: "liters" },
      { name: "white wine", amount: "150", unit: "ml" },
      { name: "flour", amount: "1", unit: "tbsp" },
      { name: "sugar", amount: "1", unit: "tsp" },
      { name: "dried thyme", amount: "1", unit: "tsp" },
      { name: "baguette", amount: "4", unit: "thick slices" },
      { name: "gruyère cheese", amount: "150", unit: "g grated" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "pepper", amount: "1/4", unit: "tsp" },
    ],
    steps: [
      "Thinly slice onions. Melt butter in a large pot over medium-low heat.",
      "Add onions with sugar and salt. Cook 45–50 minutes, stirring every 5–10 minutes, until deeply caramelized and dark amber.",
      "Add flour, stir 1 minute. Pour in white wine and scrape the bottom. Add broth and thyme.",
      "Simmer 15 minutes. Adjust seasoning.",
      "Preheat oven to 400°F / 200°C. Ladle soup into oven-safe bowls. Float a baguette slice on top.",
      "Pile gruyère generously over the bread. Bake 10 minutes, then broil 2–3 minutes until bubbling and golden.",
    ],
  },
  {
    id: 68, name: "Ratatouille", image: "🫕",
    time: { prep: 20, cook: 60, total: 80 }, servings: 4, difficulty: "Medium",
    temperature: { f: 375, c: 190 },
    equipment: ["Oven", "Baking Dish", "Stove", "Pan", "Oven Mitts"],
    tags: ["French", "Dinner", "Vegetarian", "Healthy"],
    ingredients: [
      { name: "zucchini", amount: "2", unit: "medium" },
      { name: "eggplant", amount: "1", unit: "medium" },
      { name: "tomatoes", amount: "4", unit: "medium" },
      { name: "bell pepper", amount: "1", unit: "red" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "canned tomatoes", amount: "200", unit: "g" },
      { name: "olive oil", amount: "5", unit: "tbsp" },
      { name: "dried thyme", amount: "1", unit: "tsp" },
      { name: "fresh basil", amount: "handful", unit: "" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Preheat oven to 375°F / 190°C.",
      "Sauté diced onion and pepper in olive oil 5 minutes. Add minced garlic, canned tomatoes, and thyme. Simmer 10 minutes to form the sauce. Pour into a baking dish.",
      "Thinly slice zucchini, eggplant, and fresh tomatoes into rounds.",
      "Arrange the vegetable slices in overlapping concentric circles on top of the sauce, alternating types.",
      "Drizzle with olive oil. Season with salt.",
      "Cover with foil and bake 40 minutes. Uncover and bake another 15 minutes.",
      "Garnish with fresh basil. Serve warm or at room temperature.",
    ],
  },
];
