const RECIPES = [
  // ── General ──────────────────────────────────────────────────
  {
    id: 1,
    name: "Classic Scrambled Eggs",
    image: "🍳",
    time: { prep: 2, cook: 5, total: 7 },
    servings: 2,
    difficulty: "Easy",
    equipment: ["Stove", "Pan", "Spatula"],
    tags: ["Breakfast", "Quick"],
    ingredients: [
      { name: "eggs", amount: "4", unit: "large" },
      { name: "butter", amount: "1", unit: "tbsp" },
      { name: "milk", amount: "2", unit: "tbsp" },
      { name: "salt", amount: "1/4", unit: "tsp" },
      { name: "pepper", amount: "1/4", unit: "tsp" },
    ],
    steps: [
      "Crack eggs into a bowl, add milk, salt, and pepper. Whisk until fully combined.",
      "Melt butter in a non-stick pan over medium-low heat.",
      "Pour in the egg mixture and let it sit for 20 seconds.",
      "Using a spatula, gently push the eggs from the edges toward the center.",
      "Continue folding slowly until eggs are just set but still slightly glossy.",
      "Remove from heat immediately and serve.",
    ],
  },
  {
    id: 2,
    name: "Garlic Pasta",
    image: "🍝",
    time: { prep: 5, cook: 20, total: 25 },
    servings: 2,
    difficulty: "Easy",
    equipment: ["Stove", "Large Pot", "Pan", "Colander"],
    tags: ["Dinner", "Italian", "Vegetarian"],
    ingredients: [
      { name: "pasta", amount: "200", unit: "g" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "olive oil", amount: "4", unit: "tbsp" },
      { name: "parmesan cheese", amount: "50", unit: "g" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "pepper", amount: "1/4", unit: "tsp" },
      { name: "fresh parsley", amount: "handful", unit: "" },
    ],
    steps: [
      "Bring a large pot of salted water to a boil. Cook pasta according to package directions until al dente.",
      "While pasta cooks, thinly slice the garlic cloves.",
      "Heat olive oil in a pan over medium-low heat. Add garlic and cook gently for 3–4 minutes until golden — don't let it burn.",
      "Reserve 1/2 cup of pasta water, then drain the pasta.",
      "Add pasta to the pan with garlic oil. Toss to coat, adding pasta water a splash at a time if needed.",
      "Remove from heat, toss with grated parmesan and chopped parsley.",
      "Season with salt and pepper. Serve immediately.",
    ],
  },
  {
    id: 3,
    name: "Tomato Soup",
    image: "🍅",
    time: { prep: 10, cook: 30, total: 40 },
    servings: 4,
    difficulty: "Easy",
    equipment: ["Stove", "Large Pot", "Blender"],
    tags: ["Lunch", "Vegetarian", "Comfort Food"],
    ingredients: [
      { name: "canned tomatoes", amount: "800", unit: "g" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "vegetable broth", amount: "2", unit: "cups" },
      { name: "sugar", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "pepper", amount: "1/4", unit: "tsp" },
      { name: "fresh basil", amount: "handful", unit: "" },
    ],
    steps: [
      "Dice the onion and mince the garlic.",
      "Heat olive oil in a large pot over medium heat. Add onion and cook 5 minutes until soft.",
      "Add garlic and cook 1 more minute.",
      "Pour in the canned tomatoes and vegetable broth. Add sugar, salt, and pepper.",
      "Bring to a boil, then reduce heat and simmer for 20 minutes.",
      "Remove from heat and blend until smooth using a blender or immersion blender.",
      "Taste and adjust seasoning. Serve topped with fresh basil.",
    ],
  },
  {
    id: 4,
    name: "Banana Pancakes",
    image: "🥞",
    time: { prep: 5, cook: 15, total: 20 },
    servings: 2,
    difficulty: "Easy",
    equipment: ["Stove", "Pan", "Mixing Bowl", "Spatula"],
    tags: ["Breakfast", "Sweet"],
    ingredients: [
      { name: "banana", amount: "2", unit: "ripe" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "flour", amount: "1/2", unit: "cup" },
      { name: "milk", amount: "1/4", unit: "cup" },
      { name: "baking powder", amount: "1", unit: "tsp" },
      { name: "sugar", amount: "1", unit: "tbsp" },
      { name: "butter", amount: "1", unit: "tbsp" },
      { name: "salt", amount: "pinch", unit: "" },
    ],
    steps: [
      "Mash the bananas in a bowl until smooth.",
      "Add eggs and milk to the bananas. Mix well.",
      "Stir in flour, baking powder, sugar, and salt until just combined — a few lumps are fine.",
      "Melt a small amount of butter in a non-stick pan over medium heat.",
      "Pour about 1/4 cup of batter per pancake. Cook until bubbles form on the surface, about 2–3 minutes.",
      "Flip and cook another 1–2 minutes until golden.",
      "Serve with maple syrup or fresh fruit.",
    ],
  },
  {
    id: 5,
    name: "Fried Rice",
    image: "🍚",
    time: { prep: 10, cook: 15, total: 25 },
    servings: 3,
    difficulty: "Medium",
    equipment: ["Stove", "Wok or Large Pan", "Spatula"],
    tags: ["Dinner", "Asian", "Leftovers"],
    ingredients: [
      { name: "cooked rice", amount: "3", unit: "cups" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "soy sauce", amount: "3", unit: "tbsp" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "onion", amount: "1", unit: "small" },
      { name: "vegetable oil", amount: "2", unit: "tbsp" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
      { name: "frozen peas", amount: "1/2", unit: "cup" },
      { name: "carrot", amount: "1", unit: "medium" },
    ],
    steps: [
      "Dice onion and carrot into small pieces. Mince garlic.",
      "Heat vegetable oil in a wok or large pan over high heat.",
      "Add onion and carrot, stir-fry for 3 minutes.",
      "Add garlic and stir-fry for 30 seconds.",
      "Push everything to the side and scramble the eggs in the empty space. Break them up as they cook.",
      "Add cold rice, breaking up any clumps. Stir everything together.",
      "Add peas, soy sauce, and sesame oil. Toss and stir-fry for 3–4 minutes until rice is hot and slightly crispy.",
      "Taste and adjust seasoning. Serve immediately.",
    ],
  },
  {
    id: 6,
    name: "Avocado Toast",
    image: "🥑",
    time: { prep: 5, cook: 5, total: 10 },
    servings: 2,
    difficulty: "Easy",
    equipment: ["Toaster", "Knife"],
    tags: ["Breakfast", "Quick", "Vegetarian"],
    ingredients: [
      { name: "bread", amount: "2", unit: "slices" },
      { name: "avocado", amount: "1", unit: "ripe" },
      { name: "lemon", amount: "1/2", unit: "" },
      { name: "salt", amount: "1/4", unit: "tsp" },
      { name: "pepper", amount: "1/4", unit: "tsp" },
      { name: "red pepper flakes", amount: "pinch", unit: "" },
    ],
    steps: [
      "Toast the bread slices to your desired level.",
      "Halve the avocado, remove the pit, and scoop the flesh into a bowl.",
      "Add lemon juice, salt, and pepper. Mash to your preferred texture — chunky or smooth.",
      "Spread the avocado mixture over the toasted bread.",
      "Sprinkle with red pepper flakes and an extra pinch of salt.",
      "Serve immediately.",
    ],
  },
  {
    id: 7,
    name: "Roasted Chicken Thighs",
    image: "🍗",
    time: { prep: 10, cook: 40, total: 50 },
    servings: 4,
    difficulty: "Easy",
    temperature: { f: 425, c: 220 },
    equipment: ["Oven", "Baking Dish", "Oven Mitts"],
    tags: ["Dinner", "Protein"],
    ingredients: [
      { name: "chicken thighs", amount: "4", unit: "bone-in" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "paprika", amount: "1", unit: "tsp" },
      { name: "dried thyme", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "pepper", amount: "1/2", unit: "tsp" },
      { name: "lemon", amount: "1", unit: "" },
    ],
    steps: [
      "Preheat oven to 425°F / 220°C.",
      "Pat chicken thighs dry with paper towels.",
      "Mix olive oil, minced garlic, paprika, thyme, salt, and pepper in a small bowl.",
      "Rub the mixture all over the chicken thighs.",
      "Place in a baking dish, skin-side up.",
      "Squeeze lemon juice over the chicken.",
      "Roast for 35–40 minutes until skin is golden and crispy, and internal temperature reaches 165°F / 74°C.",
      "Let rest 5 minutes before serving.",
    ],
  },
  {
    id: 8,
    name: "Greek Salad",
    image: "🥗",
    time: { prep: 15, cook: 0, total: 15 },
    servings: 4,
    difficulty: "Easy",
    equipment: ["Knife", "Cutting Board", "Mixing Bowl"],
    tags: ["Lunch", "Salad", "Vegetarian", "No-Cook"],
    ingredients: [
      { name: "cucumber", amount: "1", unit: "large" },
      { name: "tomatoes", amount: "3", unit: "medium" },
      { name: "red onion", amount: "1/2", unit: "" },
      { name: "olives", amount: "1/2", unit: "cup" },
      { name: "feta cheese", amount: "150", unit: "g" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "red wine vinegar", amount: "1", unit: "tbsp" },
      { name: "dried oregano", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "pepper", amount: "1/4", unit: "tsp" },
    ],
    steps: [
      "Chop the cucumber into chunky half-moons.",
      "Quarter the tomatoes.",
      "Thinly slice the red onion.",
      "Combine cucumber, tomatoes, onion, and olives in a large bowl.",
      "Whisk together olive oil, red wine vinegar, oregano, salt, and pepper.",
      "Pour dressing over the salad and toss gently.",
      "Crumble feta cheese on top. Serve immediately or chill for 10 minutes.",
    ],
  },
  {
    id: 9,
    name: "Baked Potatoes",
    image: "🥔",
    time: { prep: 5, cook: 60, total: 65 },
    servings: 2,
    difficulty: "Easy",
    temperature: { f: 425, c: 220 },
    equipment: ["Oven", "Oven Mitts", "Fork"],
    tags: ["Dinner", "Side Dish", "Vegetarian"],
    ingredients: [
      { name: "potatoes", amount: "2", unit: "large russet" },
      { name: "olive oil", amount: "1", unit: "tbsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "butter", amount: "2", unit: "tbsp" },
      { name: "sour cream", amount: "4", unit: "tbsp" },
      { name: "cheddar cheese", amount: "1/2", unit: "cup shredded" },
      { name: "chives", amount: "2", unit: "tbsp chopped" },
    ],
    steps: [
      "Preheat oven to 425°F / 220°C.",
      "Scrub potatoes clean and pat dry. Pierce all over with a fork.",
      "Rub with olive oil and sprinkle with salt.",
      "Place directly on the oven rack and bake for 50–60 minutes until tender when pierced.",
      "Cut open, fluff the interior with a fork.",
      "Top with butter, sour cream, cheddar cheese, and chives.",
    ],
  },
  {
    id: 10,
    name: "Stir-Fry Vegetables",
    image: "🥦",
    time: { prep: 10, cook: 10, total: 20 },
    servings: 3,
    difficulty: "Easy",
    equipment: ["Stove", "Wok or Large Pan", "Spatula"],
    tags: ["Dinner", "Vegetarian", "Asian", "Healthy"],
    ingredients: [
      { name: "broccoli", amount: "2", unit: "cups florets" },
      { name: "bell pepper", amount: "1", unit: "large" },
      { name: "carrot", amount: "2", unit: "medium" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tsp fresh" },
      { name: "soy sauce", amount: "3", unit: "tbsp" },
      { name: "sesame oil", amount: "1", unit: "tsp" },
      { name: "vegetable oil", amount: "2", unit: "tbsp" },
      { name: "cornstarch", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Cut all vegetables into bite-sized pieces. Mince garlic and ginger.",
      "Mix soy sauce, sesame oil, and cornstarch in a small bowl. Set aside.",
      "Heat vegetable oil in a wok or large pan over high heat until smoking.",
      "Add carrot and stir-fry for 2 minutes.",
      "Add broccoli and bell pepper. Stir-fry for 3–4 minutes.",
      "Add garlic and ginger, stir-fry for 30 seconds.",
      "Pour in the sauce and toss everything to coat.",
      "Cook 1 more minute until sauce thickens slightly. Serve over rice.",
    ],
  },
  {
    id: 11,
    name: "Grilled Cheese Sandwich",
    image: "🧀",
    time: { prep: 2, cook: 8, total: 10 },
    servings: 1,
    difficulty: "Easy",
    equipment: ["Stove", "Pan", "Spatula"],
    tags: ["Lunch", "Quick", "Comfort Food"],
    ingredients: [
      { name: "bread", amount: "2", unit: "slices" },
      { name: "cheddar cheese", amount: "2", unit: "slices" },
      { name: "butter", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Butter one side of each bread slice.",
      "Heat a pan over medium-low heat.",
      "Place one slice of bread butter-side down in the pan.",
      "Layer the cheese slices on top.",
      "Place the second slice of bread on top, butter-side up.",
      "Cook for 3–4 minutes until the bottom is golden brown.",
      "Carefully flip and cook another 3–4 minutes until golden and cheese is melted.",
      "Slice diagonally and serve immediately.",
    ],
  },
  {
    id: 12,
    name: "Overnight Oats",
    image: "🥣",
    time: { prep: 5, cook: 0, total: 5 },
    servings: 1,
    difficulty: "Easy",
    equipment: ["Mason Jar or Bowl", "Refrigerator"],
    tags: ["Breakfast", "No-Cook", "Meal Prep"],
    ingredients: [
      { name: "rolled oats", amount: "1/2", unit: "cup" },
      { name: "milk", amount: "1/2", unit: "cup" },
      { name: "yogurt", amount: "1/4", unit: "cup" },
      { name: "chia seeds", amount: "1", unit: "tbsp" },
      { name: "honey", amount: "1", unit: "tbsp" },
      { name: "banana", amount: "1/2", unit: "" },
      { name: "berries", amount: "handful", unit: "" },
    ],
    steps: [
      "Combine oats, milk, yogurt, chia seeds, and honey in a jar or bowl.",
      "Stir well to combine.",
      "Cover and refrigerate overnight (or at least 4 hours).",
      "In the morning, stir and add a splash of milk if too thick.",
      "Top with sliced banana and fresh berries.",
      "Enjoy cold straight from the fridge.",
    ],
  },
  {
    id: 13,
    name: "Shakshuka",
    image: "🍳",
    time: { prep: 10, cook: 25, total: 35 },
    servings: 3,
    difficulty: "Medium",
    equipment: ["Stove", "Large Pan or Skillet", "Lid"],
    tags: ["Breakfast", "Lunch", "Middle Eastern", "Vegetarian"],
    ingredients: [
      { name: "eggs", amount: "4", unit: "large" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "bell pepper", amount: "1", unit: "red" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "paprika", amount: "1", unit: "tsp" },
      { name: "chili flakes", amount: "1/2", unit: "tsp" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "fresh parsley", amount: "handful", unit: "" },
    ],
    steps: [
      "Dice onion and bell pepper. Mince garlic.",
      "Heat olive oil in a large skillet over medium heat. Add onion and pepper, cook 5 minutes.",
      "Add garlic, cumin, paprika, and chili flakes. Cook 1 minute until fragrant.",
      "Pour in canned tomatoes. Crush them with a spoon. Add salt.",
      "Simmer sauce for 10 minutes, stirring occasionally, until slightly thickened.",
      "Use a spoon to make 4 wells in the sauce. Crack an egg into each well.",
      "Cover the pan and cook on medium-low for 5–8 minutes until whites are set but yolks are still runny.",
      "Garnish with fresh parsley and serve with crusty bread.",
    ],
  },
  {
    id: 14,
    name: "Lemon Herb Salmon",
    image: "🐟",
    time: { prep: 5, cook: 15, total: 20 },
    servings: 2,
    difficulty: "Easy",
    temperature: { f: 400, c: 200 },
    equipment: ["Oven", "Baking Sheet", "Oven Mitts"],
    tags: ["Dinner", "Seafood", "Healthy"],
    ingredients: [
      { name: "salmon fillets", amount: "2", unit: "6oz each" },
      { name: "lemon", amount: "1", unit: "" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "dried dill", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "pepper", amount: "1/4", unit: "tsp" },
      { name: "butter", amount: "1", unit: "tbsp" },
    ],
    steps: [
      "Preheat oven to 400°F / 200°C. Line a baking sheet with foil.",
      "Mix olive oil, minced garlic, dill, salt, and pepper.",
      "Place salmon fillets on the baking sheet.",
      "Brush the olive oil mixture over the salmon.",
      "Top each fillet with a pat of butter and 2–3 lemon slices.",
      "Bake for 12–15 minutes until salmon flakes easily with a fork.",
      "Squeeze fresh lemon juice over top before serving.",
    ],
  },
  {
    id: 15,
    name: "Black Bean Tacos",
    image: "🌮",
    time: { prep: 10, cook: 10, total: 20 },
    servings: 4,
    difficulty: "Easy",
    equipment: ["Stove", "Pan", "Knife"],
    tags: ["Dinner", "Mexican", "Vegetarian"],
    ingredients: [
      { name: "canned black beans", amount: "400", unit: "g" },
      { name: "tortillas", amount: "8", unit: "small" },
      { name: "onion", amount: "1", unit: "small" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "chili powder", amount: "1", unit: "tsp" },
      { name: "lime", amount: "1", unit: "" },
      { name: "olive oil", amount: "1", unit: "tbsp" },
      { name: "sour cream", amount: "4", unit: "tbsp" },
      { name: "cheddar cheese", amount: "1/2", unit: "cup shredded" },
      { name: "salt", amount: "1/2", unit: "tsp" },
    ],
    steps: [
      "Dice onion and mince garlic.",
      "Heat olive oil in a pan over medium heat. Add onion and cook 3 minutes.",
      "Add garlic, cumin, and chili powder. Cook 1 minute.",
      "Drain and rinse black beans. Add to the pan with a splash of water.",
      "Season with salt and cook 5 minutes, partially mashing some beans.",
      "Squeeze in lime juice and stir to combine.",
      "Warm tortillas in a dry pan or microwave.",
      "Fill each tortilla with bean mixture. Top with sour cream, shredded cheese, and any desired toppings.",
    ],
  },

  // ── More General ────────────────────────────────────────────
  {
    id: 16,
    name: "French Toast",
    image: "🍞",
    time: { prep: 5, cook: 10, total: 15 },
    servings: 2,
    difficulty: "Easy",
    equipment: ["Stove", "Pan", "Mixing Bowl", "Spatula"],
    tags: ["Breakfast", "Sweet"],
    ingredients: [
      { name: "bread", amount: "4", unit: "thick slices" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "milk", amount: "1/4", unit: "cup" },
      { name: "sugar", amount: "1", unit: "tbsp" },
      { name: "vanilla extract", amount: "1/2", unit: "tsp" },
      { name: "cinnamon", amount: "1/2", unit: "tsp" },
      { name: "butter", amount: "1", unit: "tbsp" },
    ],
    steps: [
      "Whisk together eggs, milk, sugar, vanilla, and cinnamon in a shallow bowl.",
      "Heat butter in a pan over medium heat.",
      "Dip each bread slice into the egg mixture, letting it soak for 10 seconds per side.",
      "Place in the pan and cook for 2–3 minutes until golden brown.",
      "Flip and cook another 2 minutes on the other side.",
      "Serve with maple syrup, powdered sugar, or fresh fruit.",
    ],
  },
  {
    id: 17,
    name: "Baked Mac and Cheese",
    image: "🧀",
    time: { prep: 15, cook: 30, total: 45 },
    servings: 4,
    difficulty: "Medium",
    temperature: { f: 375, c: 190 },
    equipment: ["Stove", "Oven", "Large Pot", "Baking Dish", "Oven Mitts"],
    tags: ["Dinner", "Comfort Food", "Vegetarian"],
    ingredients: [
      { name: "macaroni pasta", amount: "300", unit: "g" },
      { name: "cheddar cheese", amount: "200", unit: "g shredded" },
      { name: "butter", amount: "3", unit: "tbsp" },
      { name: "flour", amount: "3", unit: "tbsp" },
      { name: "milk", amount: "2", unit: "cups" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "pepper", amount: "1/4", unit: "tsp" },
      { name: "paprika", amount: "1/2", unit: "tsp" },
      { name: "breadcrumbs", amount: "1/2", unit: "cup" },
    ],
    steps: [
      "Preheat oven to 375°F / 190°C. Cook macaroni in salted water until al dente. Drain and set aside.",
      "Melt butter in the pot over medium heat. Whisk in flour and cook for 1 minute.",
      "Gradually whisk in milk, stirring constantly until the sauce thickens, about 5 minutes.",
      "Remove from heat and stir in 3/4 of the cheddar cheese. Season with salt, pepper, and paprika.",
      "Add cooked macaroni to the cheese sauce and stir to combine.",
      "Pour into a baking dish. Top with remaining cheese and breadcrumbs.",
      "Bake for 20–25 minutes until golden and bubbling.",
      "Let cool for 5 minutes before serving.",
    ],
  },
  {
    id: 18,
    name: "Vegetable Curry",
    image: "🍛",
    time: { prep: 15, cook: 30, total: 45 },
    servings: 4,
    difficulty: "Medium",
    equipment: ["Stove", "Large Pot"],
    tags: ["Dinner", "Indian", "Vegetarian", "Healthy"],
    ingredients: [
      { name: "potatoes", amount: "2", unit: "medium, diced" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tbsp fresh" },
      { name: "coconut milk", amount: "400", unit: "ml" },
      { name: "vegetable broth", amount: "1", unit: "cup" },
      { name: "curry powder", amount: "2", unit: "tbsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "vegetable oil", amount: "2", unit: "tbsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "frozen peas", amount: "1", unit: "cup" },
    ],
    steps: [
      "Dice onion, mince garlic and ginger. Dice potatoes into 2cm cubes.",
      "Heat oil in a large pot over medium heat. Add onion and cook 5 minutes until soft.",
      "Add garlic and ginger, cook 1 minute. Add curry powder and cumin, stir for 30 seconds.",
      "Add potatoes, canned tomatoes, vegetable broth, and salt. Stir to combine.",
      "Bring to a boil, then reduce heat and simmer for 15 minutes.",
      "Pour in coconut milk and add peas. Simmer another 10 minutes until potatoes are tender.",
      "Taste and adjust seasoning. Serve over basmati rice with naan bread.",
    ],
  },
  {
    id: 19,
    name: "Beef Burgers",
    image: "🍔",
    time: { prep: 10, cook: 15, total: 25 },
    servings: 4,
    difficulty: "Medium",
    equipment: ["Stove", "Grill Pan or Pan", "Spatula"],
    tags: ["Dinner", "Grilling", "American"],
    ingredients: [
      { name: "ground beef", amount: "500", unit: "g" },
      { name: "burger buns", amount: "4", unit: "" },
      { name: "onion", amount: "1/2", unit: "" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "pepper", amount: "1/2", unit: "tsp" },
      { name: "cheddar cheese", amount: "4", unit: "slices" },
      { name: "lettuce", amount: "4", unit: "leaves" },
      { name: "tomatoes", amount: "1", unit: "sliced" },
    ],
    steps: [
      "Finely dice the onion and mince the garlic.",
      "Mix ground beef with onion, garlic, salt, and pepper. Form into 4 equal patties.",
      "Make a slight indent in the center of each patty with your thumb to prevent puffing.",
      "Heat a grill pan or heavy pan over high heat.",
      "Cook burgers for 3–4 minutes per side for medium, or 5 minutes per side for well done.",
      "Add cheese slice on top in the last minute of cooking and cover to melt.",
      "Toast buns on the pan for 1 minute. Assemble with lettuce and tomato.",
    ],
  },
  {
    id: 20,
    name: "Spaghetti Bolognese",
    image: "🍝",
    time: { prep: 10, cook: 45, total: 55 },
    servings: 4,
    difficulty: "Medium",
    equipment: ["Stove", "Large Pot", "Pan", "Colander"],
    tags: ["Dinner", "Italian", "Comfort Food"],
    ingredients: [
      { name: "spaghetti", amount: "400", unit: "g" },
      { name: "ground beef", amount: "400", unit: "g" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "carrot", amount: "1", unit: "medium" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "tomato paste", amount: "2", unit: "tbsp" },
      { name: "dried oregano", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "pepper", amount: "1/2", unit: "tsp" },
      { name: "parmesan cheese", amount: "to taste", unit: "" },
    ],
    steps: [
      "Finely dice onion and carrot. Mince garlic.",
      "Heat olive oil in a large pan over medium heat. Add onion and carrot, cook 5 minutes.",
      "Add garlic and cook 1 minute. Add ground beef and brown, breaking it up, about 5–7 minutes.",
      "Stir in tomato paste, then add canned tomatoes, oregano, salt, and pepper.",
      "Simmer on low heat for 30 minutes, stirring occasionally.",
      "Cook spaghetti in a large pot of salted boiling water until al dente. Drain.",
      "Toss pasta with sauce. Serve topped with grated parmesan.",
    ],
  },
  {
    id: 21,
    name: "Chicken Quesadillas",
    image: "🫓",
    time: { prep: 10, cook: 15, total: 25 },
    servings: 4,
    difficulty: "Easy",
    equipment: ["Stove", "Pan", "Knife", "Spatula"],
    tags: ["Lunch", "Mexican", "Quick"],
    ingredients: [
      { name: "tortillas", amount: "4", unit: "large" },
      { name: "chicken breast", amount: "300", unit: "g" },
      { name: "cheddar cheese", amount: "150", unit: "g shredded" },
      { name: "bell pepper", amount: "1", unit: "" },
      { name: "onion", amount: "1/2", unit: "" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "chili powder", amount: "1/2", unit: "tsp" },
      { name: "olive oil", amount: "1", unit: "tbsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "sour cream", amount: "to serve", unit: "" },
    ],
    steps: [
      "Slice chicken into thin strips. Slice bell pepper and onion.",
      "Heat olive oil in a pan over medium-high heat. Cook chicken with cumin, chili powder, and salt for 6–8 minutes until cooked through.",
      "Remove chicken. In the same pan, sauté peppers and onion for 3 minutes.",
      "Lay a tortilla in the pan over medium heat. Add chicken, peppers, and cheese on one half.",
      "Fold the tortilla over and press gently. Cook 2 minutes per side until golden and cheese melts.",
      "Slice into wedges and serve with sour cream.",
    ],
  },
  {
    id: 22,
    name: "Chocolate Chip Cookies",
    image: "🍪",
    time: { prep: 15, cook: 12, total: 27 },
    servings: 24,
    difficulty: "Easy",
    temperature: { f: 375, c: 190 },
    equipment: ["Oven", "Baking Sheet", "Mixing Bowl", "Oven Mitts"],
    tags: ["Dessert", "Sweet", "Baking"],
    ingredients: [
      { name: "flour", amount: "2 1/4", unit: "cups" },
      { name: "butter", amount: "230", unit: "g, softened" },
      { name: "sugar", amount: "3/4", unit: "cup" },
      { name: "brown sugar", amount: "3/4", unit: "cup packed" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "vanilla extract", amount: "1", unit: "tsp" },
      { name: "baking soda", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "chocolate chips", amount: "350", unit: "g" },
    ],
    steps: [
      "Preheat oven to 375°F / 190°C. Line baking sheets with parchment paper.",
      "Beat softened butter, sugar, and brown sugar together until light and fluffy.",
      "Add eggs one at a time, then mix in vanilla extract.",
      "Gradually mix in flour, baking soda, and salt until just combined.",
      "Fold in chocolate chips.",
      "Drop rounded tablespoons of dough onto the baking sheets, spaced 5cm apart.",
      "Bake for 9–12 minutes until edges are golden but centers look slightly underdone.",
      "Cool on the baking sheet for 5 minutes before transferring — they firm up as they cool.",
    ],
  },
  {
    id: 23,
    name: "Minestrone Soup",
    image: "🥣",
    time: { prep: 15, cook: 35, total: 50 },
    servings: 6,
    difficulty: "Easy",
    equipment: ["Stove", "Large Pot"],
    tags: ["Lunch", "Italian", "Vegetarian", "Healthy"],
    ingredients: [
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "canned white beans", amount: "400", unit: "g" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "carrot", amount: "2", unit: "medium" },
      { name: "celery", amount: "2", unit: "stalks" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "zucchini", amount: "1", unit: "medium" },
      { name: "pasta", amount: "100", unit: "g small" },
      { name: "vegetable broth", amount: "1.5", unit: "liters" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "dried oregano", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "parmesan cheese", amount: "to serve", unit: "" },
    ],
    steps: [
      "Dice onion, carrots, celery, and zucchini. Mince garlic.",
      "Heat olive oil in a large pot over medium heat. Add onion, carrot, and celery. Cook 5 minutes.",
      "Add garlic and oregano, cook 1 minute.",
      "Add canned tomatoes, vegetable broth, and salt. Bring to a boil.",
      "Reduce heat and simmer for 15 minutes.",
      "Add zucchini, white beans, and pasta. Simmer 10–12 more minutes until pasta is tender.",
      "Taste and adjust seasoning. Serve with grated parmesan and crusty bread.",
    ],
  },

  // ── Spanish ──────────────────────────────────────────────────
  {
    id: 24,
    name: "Tortilla Española",
    image: "🍳",
    time: { prep: 15, cook: 30, total: 45 },
    servings: 4,
    difficulty: "Medium",
    equipment: ["Stove", "Non-stick Pan", "Spatula", "Large Plate"],
    tags: ["Spanish", "Breakfast", "Lunch", "Vegetarian"],
    ingredients: [
      { name: "eggs", amount: "6", unit: "large" },
      { name: "potatoes", amount: "500", unit: "g" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "olive oil", amount: "1/2", unit: "cup" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Peel and thinly slice the potatoes (2–3mm thick). Thinly slice the onion.",
      "Heat olive oil in a 24cm non-stick pan over medium heat. Add potatoes and onion with salt.",
      "Cook gently for 20–25 minutes, stirring occasionally, until potatoes are tender but not crispy. Remove with a slotted spoon and drain excess oil.",
      "Beat eggs well in a large bowl. Add the potato-onion mixture and mix. Let sit 5 minutes.",
      "Heat 2 tbsp of oil in the pan over medium heat. Pour in the egg-potato mixture.",
      "Cook for 4–5 minutes until the edges are set but the center is still slightly runny.",
      "Place a large plate over the pan and flip the tortilla onto it. Slide it back into the pan uncooked-side down.",
      "Cook another 3–4 minutes until set. Serve warm or at room temperature.",
    ],
  },
  {
    id: 25,
    name: "Gazpacho",
    image: "🥣",
    time: { prep: 15, cook: 0, total: 15 },
    servings: 4,
    difficulty: "Easy",
    equipment: ["Blender", "Knife", "Cutting Board"],
    tags: ["Spanish", "Soup", "No-Cook", "Vegetarian", "Healthy"],
    ingredients: [
      { name: "tomatoes", amount: "700", unit: "g ripe" },
      { name: "cucumber", amount: "1/2", unit: "large" },
      { name: "red bell pepper", amount: "1/2", unit: "" },
      { name: "garlic", amount: "1", unit: "clove" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "red wine vinegar", amount: "2", unit: "tbsp" },
      { name: "stale bread", amount: "1", unit: "slice" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "cold water", amount: "1/2", unit: "cup" },
    ],
    steps: [
      "Roughly chop tomatoes, cucumber, and bell pepper. Remove seeds if preferred.",
      "Soak the stale bread in water for 2 minutes, then squeeze out the excess.",
      "Add all ingredients to a blender: tomatoes, cucumber, pepper, garlic, soaked bread, olive oil, vinegar, salt, and cold water.",
      "Blend on high for 2–3 minutes until completely smooth.",
      "Taste and adjust salt and vinegar.",
      "Refrigerate for at least 1 hour before serving — gazpacho is always served cold.",
      "Serve in bowls with a drizzle of olive oil and diced cucumber or croutons on top.",
    ],
  },
  {
    id: 26,
    name: "Patatas Bravas",
    image: "🥔",
    time: { prep: 10, cook: 40, total: 50 },
    servings: 4,
    difficulty: "Easy",
    temperature: { f: 425, c: 220 },
    equipment: ["Oven", "Baking Sheet", "Stove", "Small Pan", "Oven Mitts"],
    tags: ["Spanish", "Side Dish", "Tapas", "Vegetarian"],
    ingredients: [
      { name: "potatoes", amount: "800", unit: "g" },
      { name: "olive oil", amount: "4", unit: "tbsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "canned tomatoes", amount: "200", unit: "g" },
      { name: "paprika", amount: "1", unit: "tsp smoked" },
      { name: "chili flakes", amount: "1/2", unit: "tsp" },
      { name: "sugar", amount: "1/2", unit: "tsp" },
      { name: "mayonnaise", amount: "4", unit: "tbsp" },
      { name: "lemon", amount: "1/2", unit: "" },
    ],
    steps: [
      "Preheat oven to 425°F / 220°C. Cut potatoes into rough 3cm chunks.",
      "Toss potatoes with 3 tbsp olive oil and 3/4 tsp salt. Spread on a baking sheet.",
      "Roast for 35–40 minutes, turning once halfway, until golden and crispy.",
      "Meanwhile, heat 1 tbsp olive oil in a small pan. Add minced garlic and cook 30 seconds.",
      "Add canned tomatoes, smoked paprika, chili flakes, and sugar. Simmer for 10 minutes until thickened.",
      "For aioli: mix mayonnaise with lemon juice and a small pinch of garlic.",
      "Pour the spicy tomato brava sauce over the crispy potatoes. Serve with aioli on the side.",
    ],
  },
  {
    id: 27,
    name: "Pan con Tomate",
    image: "🍅",
    time: { prep: 5, cook: 5, total: 10 },
    servings: 4,
    difficulty: "Easy",
    equipment: ["Toaster or Grill", "Knife"],
    tags: ["Spanish", "Breakfast", "Tapas", "Vegetarian", "Quick"],
    ingredients: [
      { name: "rustic bread", amount: "4", unit: "thick slices" },
      { name: "tomatoes", amount: "2", unit: "ripe" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
    ],
    steps: [
      "Toast or grill the bread slices until golden and crispy.",
      "While the bread is hot, rub the cut side of a garlic clove firmly over each slice.",
      "Halve the tomatoes and rub the cut side over the bread, pressing to release the pulp and juice — the skin should be left behind.",
      "Drizzle generously with olive oil and sprinkle with salt.",
      "Serve immediately. Optionally top with jamón (cured ham) or anchovies.",
    ],
  },
  {
    id: 28,
    name: "Albóndigas en Salsa",
    image: "🍖",
    time: { prep: 20, cook: 35, total: 55 },
    servings: 4,
    difficulty: "Medium",
    equipment: ["Stove", "Large Pan", "Mixing Bowl"],
    tags: ["Spanish", "Dinner", "Tapas", "Comfort Food"],
    ingredients: [
      { name: "ground beef", amount: "400", unit: "g" },
      { name: "ground pork", amount: "200", unit: "g" },
      { name: "eggs", amount: "1", unit: "large" },
      { name: "garlic", amount: "5", unit: "cloves" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "flour", amount: "3", unit: "tbsp" },
      { name: "fresh parsley", amount: "2", unit: "tbsp chopped" },
      { name: "paprika", amount: "1", unit: "tsp smoked" },
      { name: "cumin", amount: "1/2", unit: "tsp" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "white wine", amount: "1/2", unit: "cup" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "pepper", amount: "1/2", unit: "tsp" },
    ],
    steps: [
      "In a bowl, combine ground beef, ground pork, 2 minced garlic cloves, parsley, egg, salt, pepper, and cumin. Mix well.",
      "Roll mixture into small balls about 3cm in diameter. Lightly coat each in flour.",
      "Heat 2 tbsp olive oil in a large pan over medium-high heat. Brown the meatballs on all sides, about 5 minutes. Remove and set aside.",
      "In the same pan, heat 1 tbsp oil over medium heat. Add diced onion and cook 5 minutes.",
      "Add remaining garlic and smoked paprika, cook 1 minute.",
      "Pour in white wine and let it reduce by half, about 2 minutes.",
      "Add canned tomatoes, crushing them. Return meatballs to the pan.",
      "Simmer uncovered for 20 minutes until the sauce thickens and meatballs are cooked through.",
      "Garnish with fresh parsley and serve with bread.",
    ],
  },
  {
    id: 29,
    name: "Arroz con Leche",
    image: "🍚",
    time: { prep: 5, cook: 45, total: 50 },
    servings: 4,
    difficulty: "Easy",
    equipment: ["Stove", "Medium Pot"],
    tags: ["Spanish", "Dessert", "Sweet"],
    ingredients: [
      { name: "short-grain rice", amount: "150", unit: "g" },
      { name: "milk", amount: "1", unit: "liter" },
      { name: "sugar", amount: "100", unit: "g" },
      { name: "cinnamon stick", amount: "1", unit: "" },
      { name: "lemon", amount: "1", unit: "zest only" },
      { name: "ground cinnamon", amount: "1", unit: "tsp to serve" },
      { name: "salt", amount: "pinch", unit: "" },
    ],
    steps: [
      "Combine rice, milk, cinnamon stick, lemon zest, and a pinch of salt in a medium pot.",
      "Bring to a gentle simmer over medium heat, stirring to prevent sticking.",
      "Reduce heat to low. Cook uncovered for 35–40 minutes, stirring frequently, until the rice is very soft and the mixture is creamy.",
      "Stir in the sugar during the last 10 minutes of cooking.",
      "Remove the cinnamon stick and lemon zest. The pudding will thicken more as it cools.",
      "Pour into serving bowls and dust with ground cinnamon.",
      "Serve warm or refrigerate and serve cold — both are traditional.",
    ],
  },
  {
    id: 30,
    name: "Paella de Verduras",
    image: "🥘",
    time: { prep: 15, cook: 35, total: 50 },
    servings: 4,
    difficulty: "Medium",
    equipment: ["Stove", "Wide Pan or Paella Pan"],
    tags: ["Spanish", "Dinner", "Vegetarian", "Rice"],
    ingredients: [
      { name: "short-grain rice", amount: "300", unit: "g" },
      { name: "vegetable broth", amount: "750", unit: "ml warm" },
      { name: "bell pepper", amount: "2", unit: "red and yellow" },
      { name: "tomatoes", amount: "2", unit: "ripe" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "frozen peas", amount: "1", unit: "cup" },
      { name: "green beans", amount: "100", unit: "g" },
      { name: "olive oil", amount: "4", unit: "tbsp" },
      { name: "paprika", amount: "1", unit: "tsp smoked" },
      { name: "saffron", amount: "pinch", unit: "" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "lemon", amount: "1", unit: "to serve" },
    ],
    steps: [
      "Warm the vegetable broth and add saffron to it. Let steep while you prepare the rest.",
      "Dice onion, slice bell peppers into strips, grate or finely dice tomatoes, mince garlic.",
      "Heat olive oil in a wide pan or paella pan over medium-high heat. Add bell peppers and cook 5 minutes.",
      "Add onion and garlic, cook 3 minutes. Add tomatoes and smoked paprika, cook 5 minutes until reduced.",
      "Spread the rice evenly across the pan. Stir to coat in the sofrito.",
      "Pour in the warm saffron broth and add salt. Distribute peas and green beans on top.",
      "Bring to a boil, then reduce to a steady simmer. Do NOT stir from this point on.",
      "Cook for 18–20 minutes until the rice has absorbed the liquid. In the last 2 minutes, raise the heat briefly to create the socarrat (crispy bottom).",
      "Remove from heat, cover with foil, and rest 5 minutes. Serve with lemon wedges.",
    ],
  },
];
