const RECIPES3 = [
  // ── French (continued) ───────────────────────────────────────
  {
    id: 69, name: "Quiche Lorraine", image: "🥧",
    time: { prep: 20, cook: 45, total: 65 }, servings: 6, difficulty: "Medium",
    temperature: { f: 375, c: 190 },
    equipment: ["Oven", "Pie Dish", "Mixing Bowl", "Oven Mitts"],
    tags: ["French", "Breakfast", "Lunch", "Baking"],
    ingredients: [
      { name: "shortcrust pastry", amount: "1", unit: "sheet" },
      { name: "bacon", amount: "150", unit: "g" },
      { name: "eggs", amount: "3", unit: "large" },
      { name: "heavy cream", amount: "200", unit: "ml" },
      { name: "milk", amount: "100", unit: "ml" },
      { name: "gruyère cheese", amount: "80", unit: "g grated" },
      { name: "nutmeg", amount: "pinch", unit: "" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "pepper", amount: "1/4", unit: "tsp" },
    ],
    steps: [
      "Preheat oven to 375°F / 190°C. Press pastry into a pie dish and blind bake with weights for 15 minutes. Remove weights and bake 5 more minutes.",
      "Fry bacon until crispy. Drain and scatter over the pastry base.",
      "Whisk eggs, cream, milk, nutmeg, salt, and pepper together.",
      "Scatter half the cheese over the bacon. Pour in the egg mixture. Top with remaining cheese.",
      "Bake 30–35 minutes until just set with a slight wobble in the center.",
      "Cool at least 10 minutes before slicing. Serve warm or at room temperature.",
    ],
  },
  {
    id: 70, name: "Crème Brûlée", image: "🍮",
    time: { prep: 15, cook: 45, total: 60 }, servings: 4, difficulty: "Medium",
    temperature: { f: 325, c: 160 },
    equipment: ["Oven", "Ramekins", "Mixing Bowl", "Kitchen Torch", "Roasting Pan"],
    tags: ["French", "Dessert", "Sweet"],
    ingredients: [
      { name: "heavy cream", amount: "500", unit: "ml" },
      { name: "eggs", amount: "5", unit: "yolks only" },
      { name: "sugar", amount: "100", unit: "g" },
      { name: "vanilla extract", amount: "1", unit: "tsp" },
      { name: "brown sugar", amount: "4", unit: "tbsp for topping" },
    ],
    steps: [
      "Preheat oven to 325°F / 160°C.",
      "Heat cream until just steaming. Do not boil.",
      "Whisk egg yolks and sugar until pale. Slowly pour in hot cream while whisking constantly.",
      "Add vanilla. Skim off any foam.",
      "Pour into 4 ramekins. Place in a deep roasting pan and fill with hot water halfway up the ramekins.",
      "Bake 35–40 minutes until set with a gentle wobble. Cool, then refrigerate at least 2 hours.",
      "Sprinkle brown sugar evenly over each ramekin. Torch until caramelized and crackly.",
    ],
  },
  {
    id: 71, name: "Croque Monsieur", image: "🥪",
    time: { prep: 10, cook: 15, total: 25 }, servings: 2, difficulty: "Easy",
    temperature: { f: 400, c: 200 },
    equipment: ["Oven", "Stove", "Pan", "Baking Sheet"],
    tags: ["French", "Lunch", "Sandwich"],
    ingredients: [
      { name: "bread", amount: "4", unit: "thick slices" },
      { name: "ham", amount: "4", unit: "slices" },
      { name: "gruyère cheese", amount: "80", unit: "g grated" },
      { name: "butter", amount: "2", unit: "tbsp" },
      { name: "flour", amount: "1", unit: "tbsp" },
      { name: "milk", amount: "150", unit: "ml" },
      { name: "nutmeg", amount: "pinch", unit: "" },
      { name: "salt", amount: "1/4", unit: "tsp" },
    ],
    steps: [
      "Make béchamel: melt butter, whisk in flour 1 minute, then gradually add milk until thick. Season with salt and nutmeg.",
      "Preheat oven to 400°F / 200°C.",
      "Spread béchamel on one side of each bread slice.",
      "Layer ham and half the cheese on 2 slices. Top with the other slices, béchamel-side up.",
      "Spread more béchamel on top. Sprinkle with remaining cheese.",
      "Bake on a baking sheet for 10–12 minutes until golden and bubbling.",
    ],
  },
  {
    id: 72, name: "Beef Bourguignon", image: "🍖",
    time: { prep: 20, cook: 150, total: 170 }, servings: 6, difficulty: "Hard",
    equipment: ["Stove", "Large Heavy Pot or Dutch Oven"],
    tags: ["French", "Dinner", "Comfort Food", "Slow Cook"],
    ingredients: [
      { name: "beef chuck", amount: "1", unit: "kg cubed" },
      { name: "red wine", amount: "750", unit: "ml Burgundy or Pinot Noir" },
      { name: "bacon", amount: "150", unit: "g lardons" },
      { name: "mushrooms", amount: "250", unit: "g" },
      { name: "pearl onions", amount: "200", unit: "g" },
      { name: "carrot", amount: "2", unit: "medium" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "tomato paste", amount: "2", unit: "tbsp" },
      { name: "beef broth", amount: "300", unit: "ml" },
      { name: "flour", amount: "2", unit: "tbsp" },
      { name: "butter", amount: "2", unit: "tbsp" },
      { name: "dried thyme", amount: "1", unit: "tsp" },
      { name: "bay leaves", amount: "2", unit: "" },
    ],
    steps: [
      "Pat beef dry and season with salt and pepper. Sear in batches in a hot Dutch oven until browned all over. Remove.",
      "Cook bacon lardons until crispy. Remove. Sauté sliced carrots and pearl onions 5 minutes.",
      "Return beef and bacon. Sprinkle with flour, stir to coat.",
      "Add wine, broth, tomato paste, garlic, thyme, and bay leaves.",
      "Bring to a boil, then reduce to the lowest simmer. Cover and cook 2–2.5 hours until beef is very tender.",
      "Sauté mushrooms in butter separately. Add to the stew in the last 20 minutes.",
      "Remove bay leaves. Adjust seasoning. Serve with crusty bread or mashed potatoes.",
    ],
  },

  // ── More Italian ─────────────────────────────────────────────
  {
    id: 73, name: "Risotto ai Funghi", image: "🍚",
    time: { prep: 10, cook: 35, total: 45 }, servings: 3, difficulty: "Medium",
    equipment: ["Stove", "Wide Pan", "Separate Pot"],
    tags: ["Italian", "Dinner", "Vegetarian", "Rice"],
    ingredients: [
      { name: "arborio rice", amount: "300", unit: "g" },
      { name: "mushrooms", amount: "300", unit: "g mixed" },
      { name: "onion", amount: "1", unit: "small" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "white wine", amount: "100", unit: "ml" },
      { name: "vegetable broth", amount: "1", unit: "liter warm" },
      { name: "parmesan cheese", amount: "60", unit: "g grated" },
      { name: "butter", amount: "3", unit: "tbsp" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "fresh thyme", amount: "3", unit: "sprigs" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Keep broth warm in a separate pot over low heat.",
      "Sauté sliced mushrooms in 1 tbsp butter and olive oil over high heat until golden. Season and set aside.",
      "In the same pan, sauté finely diced onion in remaining butter over medium heat until soft. Add garlic.",
      "Add rice, stir to coat in butter, toast 1 minute.",
      "Pour in wine and stir until absorbed.",
      "Add warm broth one ladle at a time, stirring constantly and waiting for each addition to absorb before adding the next — about 20 minutes total.",
      "Stir in mushrooms, parmesan, and a small knob of butter. Cover and rest 2 minutes. Serve immediately.",
    ],
  },
  {
    id: 74, name: "Spaghetti Carbonara", image: "🍝",
    time: { prep: 5, cook: 20, total: 25 }, servings: 2, difficulty: "Medium",
    equipment: ["Stove", "Large Pot", "Pan", "Mixing Bowl"],
    tags: ["Italian", "Dinner", "Quick"],
    ingredients: [
      { name: "spaghetti", amount: "200", unit: "g" },
      { name: "guanciale or bacon", amount: "150", unit: "g" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "eggs", amount: "2", unit: "yolks only" },
      { name: "parmesan cheese", amount: "60", unit: "g" },
      { name: "pecorino cheese", amount: "30", unit: "g" },
      { name: "black pepper", amount: "2", unit: "tsp coarsely ground" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Whisk eggs, yolks, parmesan, pecorino, and black pepper together in a bowl.",
      "Cook guanciale in a pan over medium heat until crispy. Remove from heat — keep the fat in the pan.",
      "Cook spaghetti in well-salted boiling water until al dente. Reserve 1 cup pasta water.",
      "Add hot drained pasta directly to the pan with guanciale (off heat). Toss to coat in the fat.",
      "Pour egg mixture over the pasta, tossing constantly and adding pasta water a splash at a time to create a creamy sauce — never scrambled eggs.",
      "Serve immediately with extra black pepper and cheese.",
    ],
  },
  {
    id: 75, name: "Pizza Margherita", image: "🍕",
    time: { prep: 90, cook: 12, total: 102 }, servings: 2, difficulty: "Medium",
    temperature: { f: 500, c: 260 },
    equipment: ["Oven", "Baking Sheet or Pizza Stone", "Oven Mitts"],
    tags: ["Italian", "Dinner", "Baking", "Vegetarian"],
    ingredients: [
      { name: "flour", amount: "300", unit: "g bread flour" },
      { name: "instant yeast", amount: "7", unit: "g" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "warm water", amount: "200", unit: "ml" },
      { name: "canned tomatoes", amount: "200", unit: "g" },
      { name: "mozzarella cheese", amount: "150", unit: "g" },
      { name: "fresh basil", amount: "handful", unit: "" },
      { name: "garlic", amount: "1", unit: "clove" },
    ],
    steps: [
      "Mix flour, yeast, and salt. Add water and olive oil. Knead 10 minutes until smooth. Cover and rise 1 hour.",
      "Preheat oven to its maximum (500°F / 260°C) with a baking sheet inside.",
      "Crush canned tomatoes with a clove of garlic, pinch of salt, and olive oil — no cooking needed.",
      "Stretch dough thinly on a floured surface. Transfer to a sheet of parchment.",
      "Spread tomato sauce thinly, leaving a 2cm border. Tear mozzarella over the top.",
      "Slide onto the hot baking sheet. Bake 10–12 minutes until crust is charred at the edges and cheese bubbles.",
      "Top with fresh basil and a drizzle of olive oil.",
    ],
  },
  {
    id: 76, name: "Tiramisu", image: "🍰",
    time: { prep: 30, cook: 0, total: 30 }, servings: 6, difficulty: "Medium",
    equipment: ["Mixing Bowl", "Electric Mixer", "Baking Dish", "Refrigerator"],
    tags: ["Italian", "Dessert", "Sweet", "No-Cook"],
    ingredients: [
      { name: "ladyfinger biscuits", amount: "200", unit: "g" },
      { name: "mascarpone cheese", amount: "500", unit: "g" },
      { name: "eggs", amount: "4", unit: "large separated" },
      { name: "sugar", amount: "100", unit: "g" },
      { name: "strong espresso", amount: "250", unit: "ml cooled" },
      { name: "cocoa powder", amount: "2", unit: "tbsp" },
      { name: "coffee liqueur", amount: "2", unit: "tbsp optional" },
    ],
    steps: [
      "Beat egg yolks and sugar until thick and pale. Fold in mascarpone until smooth.",
      "Beat egg whites to stiff peaks. Gently fold into the mascarpone mixture in two batches.",
      "Mix espresso with liqueur (if using).",
      "Quickly dip each ladyfinger in the coffee — 1–2 seconds per side, don't soak.",
      "Arrange a layer of dipped ladyfingers in a dish. Spread half the cream over.",
      "Add another ladyfinger layer and top with remaining cream.",
      "Dust generously with cocoa powder. Refrigerate at least 4 hours, ideally overnight.",
    ],
  },

  // ── More Greek ───────────────────────────────────────────────
  {
    id: 77, name: "Moussaka", image: "🫕",
    time: { prep: 30, cook: 75, total: 105 }, servings: 6, difficulty: "Hard",
    temperature: { f: 375, c: 190 },
    equipment: ["Oven", "Stove", "Large Pan", "Baking Dish", "Oven Mitts"],
    tags: ["Greek", "Dinner", "Comfort Food"],
    ingredients: [
      { name: "eggplant", amount: "2", unit: "large" },
      { name: "ground beef", amount: "500", unit: "g" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "red wine", amount: "100", unit: "ml" },
      { name: "cinnamon", amount: "1/2", unit: "tsp" },
      { name: "butter", amount: "4", unit: "tbsp" },
      { name: "flour", amount: "4", unit: "tbsp" },
      { name: "milk", amount: "500", unit: "ml" },
      { name: "eggs", amount: "2", unit: "yolks only" },
      { name: "parmesan cheese", amount: "50", unit: "g" },
      { name: "olive oil", amount: "4", unit: "tbsp" },
      { name: "salt", amount: "1.5", unit: "tsp" },
    ],
    steps: [
      "Preheat oven to 375°F / 190°C. Slice eggplant 1cm thick, brush with olive oil, season with salt. Roast on baking sheets 20 minutes until golden.",
      "Brown beef with onion and garlic. Add wine, canned tomatoes, cinnamon, and salt. Simmer 20 minutes until thick.",
      "Make béchamel: melt butter, whisk in flour, gradually add milk stirring until thick. Remove from heat, whisk in egg yolks and half the parmesan.",
      "Layer eggplant in a baking dish. Spread all the meat sauce over. Top with all the béchamel. Sprinkle remaining parmesan.",
      "Bake 40–45 minutes until deep golden on top.",
      "Cool at least 20 minutes before cutting — it slices much better when not steaming hot.",
    ],
  },
  {
    id: 78, name: "Spanakopita", image: "🥧",
    time: { prep: 30, cook: 45, total: 75 }, servings: 8, difficulty: "Medium",
    temperature: { f: 375, c: 190 },
    equipment: ["Oven", "Baking Dish", "Stove", "Pan", "Oven Mitts"],
    tags: ["Greek", "Lunch", "Vegetarian", "Baking"],
    ingredients: [
      { name: "spinach", amount: "500", unit: "g fresh" },
      { name: "feta cheese", amount: "300", unit: "g" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "spring onions", amount: "4", unit: "stalks" },
      { name: "fresh dill", amount: "handful", unit: "" },
      { name: "filo pastry", amount: "10", unit: "sheets" },
      { name: "butter", amount: "100", unit: "g melted" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "nutmeg", amount: "pinch", unit: "" },
    ],
    steps: [
      "Preheat oven to 375°F / 190°C. Sauté onion and spring onions in olive oil 5 minutes.",
      "Wilt spinach in batches. Squeeze out ALL excess water — this is critical or the pie will be soggy.",
      "Combine drained spinach, crumbled feta, eggs, dill, and nutmeg.",
      "Brush a baking dish with butter. Layer 5 filo sheets, brushing each with melted butter.",
      "Spread filling evenly. Layer remaining 5 sheets on top, each brushed with butter. Score the top into squares.",
      "Bake 40–45 minutes until deeply golden and crisp.",
    ],
  },
  {
    id: 79, name: "Souvlaki", image: "🍢",
    time: { prep: 15, cook: 15, total: 30 }, servings: 4, difficulty: "Easy",
    equipment: ["Grill or Grill Pan", "Skewers"],
    tags: ["Greek", "Dinner", "Grilling"],
    ingredients: [
      { name: "pork tenderloin", amount: "600", unit: "g" },
      { name: "olive oil", amount: "4", unit: "tbsp" },
      { name: "lemon", amount: "1", unit: "" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "dried oregano", amount: "2", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "pepper", amount: "1/2", unit: "tsp" },
      { name: "pita bread", amount: "4", unit: "" },
      { name: "tomatoes", amount: "2", unit: "" },
      { name: "red onion", amount: "1/2", unit: "" },
      { name: "yogurt", amount: "200", unit: "g for tzatziki" },
      { name: "cucumber", amount: "1/4", unit: "" },
    ],
    steps: [
      "Cut pork into 3cm cubes. Marinate in olive oil, lemon juice, minced garlic, oregano, salt, and pepper for at least 1 hour.",
      "Thread onto skewers.",
      "Quick tzatziki: grate and squeeze dry cucumber, mix with yogurt, garlic, olive oil, and salt.",
      "Grill skewers over high heat 10–12 minutes, turning every few minutes until cooked with slight char.",
      "Warm pita on the grill.",
      "Serve pork in pita with tomato, red onion, and tzatziki.",
    ],
  },

  // ── British ──────────────────────────────────────────────────
  {
    id: 80, name: "Fish and Chips", image: "🐟",
    time: { prep: 20, cook: 35, total: 55 }, servings: 2, difficulty: "Medium",
    equipment: ["Stove", "Large Pot", "Mixing Bowl"],
    tags: ["British", "Dinner", "Comfort Food"],
    ingredients: [
      { name: "cod fillets", amount: "2", unit: "thick" },
      { name: "potatoes", amount: "4", unit: "large" },
      { name: "flour", amount: "150", unit: "g" },
      { name: "beer", amount: "150", unit: "ml cold" },
      { name: "baking powder", amount: "1", unit: "tsp" },
      { name: "vegetable oil", amount: "1.5", unit: "liters for frying" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "malt vinegar", amount: "to serve", unit: "" },
    ],
    steps: [
      "Cut potatoes into thick chips. Soak in cold water 30 minutes. Dry thoroughly.",
      "Par-fry chips at 300°F / 150°C for 5 minutes. Remove and cool completely.",
      "Make batter: whisk flour, baking powder, and salt. Whisk in cold beer until smooth. Refrigerate.",
      "Increase oil to 375°F / 190°C. Finish chips for 3–4 minutes until golden and crispy. Drain and salt.",
      "Dry fish fillets, season. Dip in batter, let excess drip off.",
      "Fry fish 4–5 minutes, turning once, until batter is golden and crisp. Drain.",
      "Serve with malt vinegar and salt.",
    ],
  },
  {
    id: 81, name: "Shepherd's Pie", image: "🥧",
    time: { prep: 20, cook: 55, total: 75 }, servings: 4, difficulty: "Medium",
    temperature: { f: 400, c: 200 },
    equipment: ["Stove", "Oven", "Large Pan", "Baking Dish", "Oven Mitts"],
    tags: ["British", "Dinner", "Comfort Food"],
    ingredients: [
      { name: "lamb mince", amount: "500", unit: "g" },
      { name: "potatoes", amount: "800", unit: "g" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "carrot", amount: "2", unit: "medium" },
      { name: "frozen peas", amount: "100", unit: "g" },
      { name: "tomato paste", amount: "2", unit: "tbsp" },
      { name: "beef broth", amount: "300", unit: "ml" },
      { name: "Worcestershire sauce", amount: "1", unit: "tbsp" },
      { name: "butter", amount: "3", unit: "tbsp" },
      { name: "milk", amount: "4", unit: "tbsp" },
      { name: "dried rosemary", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Boil peeled potatoes until soft. Drain and mash with butter and milk. Season well.",
      "Brown lamb mince in a pan over high heat. Drain excess fat.",
      "Add diced onion and carrot. Cook 5 minutes. Add tomato paste, rosemary, Worcestershire sauce, and broth.",
      "Simmer 15 minutes until sauce thickens. Add peas.",
      "Preheat oven to 400°F / 200°C. Pour meat into a baking dish. Spread mash on top and rough up with a fork.",
      "Bake 25–30 minutes until top is golden. Rest 5 minutes before serving.",
    ],
  },
  {
    id: 82, name: "Classic Scones", image: "🫓",
    time: { prep: 15, cook: 15, total: 30 }, servings: 8, difficulty: "Easy",
    temperature: { f: 425, c: 220 },
    equipment: ["Oven", "Mixing Bowl", "Baking Sheet", "Oven Mitts"],
    tags: ["British", "Breakfast", "Baking", "Sweet"],
    ingredients: [
      { name: "flour", amount: "300", unit: "g" },
      { name: "butter", amount: "75", unit: "g cold, cubed" },
      { name: "milk", amount: "150", unit: "ml" },
      { name: "sugar", amount: "50", unit: "g" },
      { name: "baking powder", amount: "2", unit: "tsp" },
      { name: "salt", amount: "pinch", unit: "" },
      { name: "eggs", amount: "1", unit: "for brushing" },
    ],
    steps: [
      "Preheat oven to 425°F / 220°C.",
      "Mix flour, baking powder, sugar, and salt. Rub in cold butter until mixture resembles breadcrumbs.",
      "Add milk and mix briefly until a dough just comes together — don't overwork.",
      "On a floured surface, gently pat to 2.5cm thick. Cut rounds with a glass or cutter.",
      "Place on a baking sheet. Brush tops with beaten egg.",
      "Bake 12–15 minutes until risen and golden.",
      "Serve warm with clotted cream and jam.",
    ],
  },

  // ── German ───────────────────────────────────────────────────
  {
    id: 83, name: "Wiener Schnitzel", image: "🥩",
    time: { prep: 15, cook: 15, total: 30 }, servings: 2, difficulty: "Easy",
    equipment: ["Stove", "Pan", "Mixing Bowl"],
    tags: ["German", "Dinner", "Austrian"],
    ingredients: [
      { name: "veal or pork cutlets", amount: "2", unit: "thin" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "breadcrumbs", amount: "100", unit: "g fine" },
      { name: "flour", amount: "60", unit: "g" },
      { name: "butter", amount: "60", unit: "g" },
      { name: "vegetable oil", amount: "4", unit: "tbsp" },
      { name: "lemon", amount: "1", unit: "" },
      { name: "salt", amount: "1/2", unit: "tsp" },
    ],
    steps: [
      "Pound cutlets to about 4mm thickness. Season with salt.",
      "Set up three bowls: flour, beaten eggs, breadcrumbs.",
      "Coat each cutlet in flour, then egg, then breadcrumbs. Press gently — don't compact the crumbs.",
      "Heat butter and oil together in a large pan over medium-high heat.",
      "Fry cutlets 2–3 minutes per side until golden. Shake the pan constantly so the breading puffs up.",
      "Drain on paper towels. Serve immediately with lemon wedge and potato salad.",
    ],
  },
  {
    id: 84, name: "Bratwurst with Sauerkraut", image: "🌭",
    time: { prep: 5, cook: 25, total: 30 }, servings: 4, difficulty: "Easy",
    equipment: ["Stove", "Grill Pan or Pan"],
    tags: ["German", "Dinner"],
    ingredients: [
      { name: "bratwurst sausages", amount: "4", unit: "" },
      { name: "sauerkraut", amount: "400", unit: "g" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "apple", amount: "1", unit: "" },
      { name: "caraway seeds", amount: "1", unit: "tsp" },
      { name: "beer", amount: "200", unit: "ml" },
      { name: "butter", amount: "1", unit: "tbsp" },
      { name: "mustard", amount: "to serve", unit: "" },
    ],
    steps: [
      "Grill or pan-fry bratwurst over medium heat for 15–18 minutes, turning frequently, until browned and cooked through.",
      "Meanwhile, melt butter in a pan. Sauté diced onion 5 minutes.",
      "Add peeled, diced apple and caraway seeds. Cook 2 minutes.",
      "Add sauerkraut and beer. Simmer 10 minutes until tender.",
      "Serve bratwurst on top of sauerkraut with mustard and crusty bread or rolls.",
    ],
  },
  {
    id: 85, name: "Soft Pretzels", image: "🥨",
    time: { prep: 30, cook: 20, total: 50 }, servings: 8, difficulty: "Medium",
    temperature: { f: 450, c: 230 },
    equipment: ["Oven", "Large Pot", "Baking Sheet", "Oven Mitts"],
    tags: ["German", "Snack", "Baking"],
    ingredients: [
      { name: "flour", amount: "500", unit: "g" },
      { name: "instant yeast", amount: "7", unit: "g" },
      { name: "sugar", amount: "1", unit: "tbsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "warm water", amount: "300", unit: "ml" },
      { name: "butter", amount: "2", unit: "tbsp melted" },
      { name: "baking soda", amount: "50", unit: "g for boiling" },
      { name: "coarse salt", amount: "to top", unit: "" },
      { name: "eggs", amount: "1", unit: "for brushing" },
    ],
    steps: [
      "Mix flour, yeast, sugar, and salt. Add water and butter. Knead 8 minutes until smooth. Rest 45 minutes.",
      "Preheat oven to 450°F / 230°C.",
      "Divide dough into 8 pieces. Roll each into a 60cm rope. Form pretzel shapes.",
      "Bring a large pot of water to a boil. Add baking soda (it will foam).",
      "Boil each pretzel 30 seconds per side. Remove and place on a lined baking sheet.",
      "Brush with beaten egg. Sprinkle with coarse salt.",
      "Bake 12–15 minutes until deep mahogany brown.",
    ],
  },

  // ── Brazilian ────────────────────────────────────────────────
  {
    id: 86, name: "Feijoada", image: "🫘",
    time: { prep: 20, cook: 90, total: 110 }, servings: 6, difficulty: "Medium",
    equipment: ["Stove", "Large Heavy Pot"],
    tags: ["Brazilian", "Dinner", "Slow Cook"],
    ingredients: [
      { name: "canned black beans", amount: "800", unit: "g" },
      { name: "pork ribs", amount: "300", unit: "g" },
      { name: "smoked sausage", amount: "200", unit: "g" },
      { name: "bacon", amount: "150", unit: "g" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "garlic", amount: "5", unit: "cloves" },
      { name: "bay leaves", amount: "3", unit: "" },
      { name: "orange", amount: "1", unit: "" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Brown pork ribs and bacon in a large heavy pot over high heat. Remove.",
      "Sauté diced onion and garlic in olive oil 5 minutes.",
      "Return meats. Add sliced sausage, beans (with liquid), bay leaves, and cumin.",
      "Add enough water to just cover. Bring to a boil.",
      "Simmer on low heat 60–70 minutes until pork is very tender and sauce thickens.",
      "Add sliced orange (placed on top) for the last 15 minutes — traditional and fragrant.",
      "Season with salt. Serve over white rice with sautéed collard greens.",
    ],
  },
  {
    id: 87, name: "Brigadeiros", image: "🍫",
    time: { prep: 5, cook: 15, total: 20 }, servings: 20, difficulty: "Easy",
    equipment: ["Stove", "Medium Pan"],
    tags: ["Brazilian", "Dessert", "Sweet"],
    ingredients: [
      { name: "sweetened condensed milk", amount: "400", unit: "g" },
      { name: "cocoa powder", amount: "4", unit: "tbsp" },
      { name: "butter", amount: "1", unit: "tbsp" },
      { name: "chocolate sprinkles", amount: "100", unit: "g" },
    ],
    steps: [
      "Combine condensed milk, cocoa powder, and butter in a medium pan.",
      "Cook over medium-low heat, stirring constantly with a spatula.",
      "Continue stirring for 10–12 minutes until mixture is thick and pulls away from the sides of the pan when stirred.",
      "Pour onto a buttered plate. Cool to room temperature, then refrigerate 1 hour.",
      "Butter your hands. Roll teaspoons of mixture into balls.",
      "Roll each ball in chocolate sprinkles. Place in mini cupcake papers.",
    ],
  },
  {
    id: 88, name: "Pão de Queijo", image: "🧀",
    time: { prep: 10, cook: 25, total: 35 }, servings: 20, difficulty: "Easy",
    temperature: { f: 400, c: 200 },
    equipment: ["Oven", "Mixing Bowl", "Mini Muffin Pan or Baking Sheet", "Oven Mitts"],
    tags: ["Brazilian", "Breakfast", "Snack", "Gluten-Free"],
    ingredients: [
      { name: "tapioca flour", amount: "300", unit: "g" },
      { name: "milk", amount: "120", unit: "ml" },
      { name: "vegetable oil", amount: "60", unit: "ml" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "parmesan cheese", amount: "100", unit: "g grated" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Preheat oven to 400°F / 200°C.",
      "Heat milk and oil together until just boiling. Pour over tapioca flour and stir.",
      "Let cool slightly, then add eggs one at a time, mixing well after each.",
      "Stir in parmesan and salt until a sticky dough forms.",
      "Spoon into a greased mini muffin pan or drop spoonfuls onto a lined baking sheet.",
      "Bake 20–25 minutes until puffed and golden.",
      "Serve warm — they deflate slightly as they cool, which is completely normal.",
    ],
  },

  // ── Turkish ──────────────────────────────────────────────────
  {
    id: 89, name: "Menemen", image: "🍳",
    time: { prep: 5, cook: 15, total: 20 }, servings: 2, difficulty: "Easy",
    equipment: ["Stove", "Pan"],
    tags: ["Turkish", "Breakfast", "Vegetarian", "Quick"],
    ingredients: [
      { name: "eggs", amount: "4", unit: "large" },
      { name: "tomatoes", amount: "3", unit: "ripe" },
      { name: "green pepper", amount: "1", unit: "long" },
      { name: "onion", amount: "1", unit: "small" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "paprika", amount: "1", unit: "tsp" },
      { name: "chili flakes", amount: "1/2", unit: "tsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "fresh parsley", amount: "handful", unit: "" },
    ],
    steps: [
      "Dice onion and pepper. Roughly chop tomatoes.",
      "Heat olive oil in a pan over medium heat. Add onion and cook 3 minutes.",
      "Add pepper, paprika, and chili flakes. Cook 2 minutes.",
      "Add tomatoes. Cook 5–7 minutes, stirring, until they break down into a sauce.",
      "Crack eggs directly into the pan. Stir gently — menemen is scrambled, not left whole.",
      "Cook 2–3 minutes until eggs are just set but still creamy.",
      "Top with parsley. Serve directly from the pan with crusty bread.",
    ],
  },
  {
    id: 90, name: "Adana Kebab", image: "🍢",
    time: { prep: 20, cook: 15, total: 35 }, servings: 4, difficulty: "Medium",
    equipment: ["Grill or Grill Pan", "Skewers", "Mixing Bowl"],
    tags: ["Turkish", "Dinner", "Grilling"],
    ingredients: [
      { name: "ground lamb", amount: "500", unit: "g" },
      { name: "ground beef", amount: "200", unit: "g" },
      { name: "onion", amount: "1/2", unit: "grated" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "paprika", amount: "1.5", unit: "tsp" },
      { name: "chili flakes", amount: "1", unit: "tsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "flat parsley", amount: "handful", unit: "" },
      { name: "flatbread", amount: "4", unit: "" },
    ],
    steps: [
      "Grate onion and squeeze out all liquid — wet onion makes kebabs fall apart.",
      "Mix lamb, beef, onion, minced garlic, paprika, chili, cumin, salt, and chopped parsley together well. Knead for 2 minutes.",
      "Refrigerate 30 minutes to firm up.",
      "Divide into portions. Mold each portion around a flat metal skewer into a long sausage shape.",
      "Grill over high heat 10–12 minutes, turning carefully every few minutes.",
      "Serve on flatbread with sliced tomato, onion, and yogurt.",
    ],
  },
  {
    id: 91, name: "Baklava", image: "🍯",
    time: { prep: 30, cook: 45, total: 75 }, servings: 20, difficulty: "Medium",
    temperature: { f: 350, c: 175 },
    equipment: ["Oven", "Baking Pan", "Small Pot", "Pastry Brush", "Oven Mitts"],
    tags: ["Turkish", "Dessert", "Sweet", "Greek", "Middle Eastern"],
    ingredients: [
      { name: "filo pastry", amount: "250", unit: "g" },
      { name: "walnuts", amount: "300", unit: "g chopped" },
      { name: "pistachios", amount: "100", unit: "g chopped" },
      { name: "butter", amount: "150", unit: "g melted" },
      { name: "sugar", amount: "200", unit: "g" },
      { name: "honey", amount: "100", unit: "g" },
      { name: "water", amount: "150", unit: "ml" },
      { name: "cinnamon", amount: "1", unit: "tsp" },
      { name: "lemon", amount: "1/2", unit: "juice" },
    ],
    steps: [
      "Preheat oven to 350°F / 175°C. Mix nuts with cinnamon.",
      "Brush a baking pan with butter. Layer 8 filo sheets, brushing each with melted butter.",
      "Spread half the nut mixture. Add 4 more buttered filo sheets. Spread remaining nuts. Top with the final 8 filo sheets, each buttered.",
      "Cut into diamonds with a sharp knife before baking.",
      "Bake 40–45 minutes until deeply golden.",
      "Make syrup: boil sugar, honey, water, and lemon juice for 5 minutes.",
      "Pour hot syrup over hot baklava immediately out of the oven. Let absorb — at least 4 hours before eating.",
    ],
  },

  // ── Russian ──────────────────────────────────────────────────
  {
    id: 92, name: "Borscht", image: "🫕",
    time: { prep: 20, cook: 60, total: 80 }, servings: 6, difficulty: "Easy",
    equipment: ["Stove", "Large Pot"],
    tags: ["Russian", "Soup", "Eastern European"],
    ingredients: [
      { name: "beetroot", amount: "3", unit: "medium" },
      { name: "cabbage", amount: "300", unit: "g" },
      { name: "potatoes", amount: "2", unit: "medium" },
      { name: "carrot", amount: "1", unit: "medium" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "canned tomatoes", amount: "200", unit: "g" },
      { name: "beef broth", amount: "1.5", unit: "liters" },
      { name: "butter", amount: "2", unit: "tbsp" },
      { name: "red wine vinegar", amount: "1", unit: "tbsp" },
      { name: "sugar", amount: "1", unit: "tsp" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "sour cream", amount: "to serve", unit: "" },
      { name: "fresh dill", amount: "handful", unit: "" },
    ],
    steps: [
      "Peel and grate beetroot. Dice potatoes and carrot. Shred cabbage. Dice onion.",
      "Sauté onion and carrot in butter for 5 minutes. Add grated beetroot and cook 5 more minutes.",
      "Add canned tomatoes, vinegar, and sugar. Cook 5 minutes.",
      "Add broth, potatoes, and cabbage. Bring to a boil.",
      "Simmer 35–40 minutes until all vegetables are very tender.",
      "Add minced garlic and season with salt.",
      "Serve topped with a generous spoonful of sour cream and fresh dill.",
    ],
  },
  {
    id: 93, name: "Beef Stroganoff", image: "🍝",
    time: { prep: 10, cook: 25, total: 35 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Large Pan"],
    tags: ["Russian", "Dinner", "Eastern European", "Comfort Food"],
    ingredients: [
      { name: "beef sirloin", amount: "500", unit: "g" },
      { name: "mushrooms", amount: "250", unit: "g" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "sour cream", amount: "200", unit: "ml" },
      { name: "beef broth", amount: "200", unit: "ml" },
      { name: "Dijon mustard", amount: "1", unit: "tbsp" },
      { name: "Worcestershire sauce", amount: "1", unit: "tbsp" },
      { name: "butter", amount: "3", unit: "tbsp" },
      { name: "flour", amount: "1", unit: "tbsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "fresh parsley", amount: "handful", unit: "" },
    ],
    steps: [
      "Slice beef thinly against the grain. Season with salt.",
      "Sear beef in butter over very high heat in batches, 1 minute per side. Remove.",
      "Sauté sliced onion and mushrooms in the same pan until golden, about 8 minutes.",
      "Add minced garlic and flour. Cook 1 minute.",
      "Pour in broth, Worcestershire, and mustard. Simmer 5 minutes.",
      "Reduce heat to low. Stir in sour cream — do not boil or it will curdle.",
      "Return beef to the pan. Heat gently 2 minutes. Serve over egg noodles or rice, garnished with parsley.",
    ],
  },

  // ── Jamaican ─────────────────────────────────────────────────
  {
    id: 94, name: "Jerk Chicken", image: "🍗",
    time: { prep: 20, cook: 45, total: 65 }, servings: 4, difficulty: "Medium",
    temperature: { f: 400, c: 200 },
    equipment: ["Oven", "Baking Sheet", "Blender", "Oven Mitts"],
    tags: ["Jamaican", "Dinner", "Spicy", "Caribbean"],
    ingredients: [
      { name: "chicken thighs", amount: "8", unit: "bone-in" },
      { name: "scotch bonnet pepper", amount: "2", unit: "" },
      { name: "spring onions", amount: "4", unit: "stalks" },
      { name: "garlic", amount: "5", unit: "cloves" },
      { name: "ginger", amount: "2", unit: "tbsp fresh" },
      { name: "soy sauce", amount: "2", unit: "tbsp" },
      { name: "lime", amount: "1", unit: "" },
      { name: "vegetable oil", amount: "2", unit: "tbsp" },
      { name: "allspice", amount: "1", unit: "tbsp ground" },
      { name: "cinnamon", amount: "1/2", unit: "tsp" },
      { name: "thyme", amount: "1", unit: "tsp dried" },
      { name: "brown sugar", amount: "1", unit: "tbsp" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Blend all ingredients except chicken into a smooth jerk paste.",
      "Score chicken thighs deeply with a knife. Coat thoroughly in jerk paste.",
      "Marinate at least 4 hours — overnight is best.",
      "Preheat oven to 400°F / 200°C.",
      "Place chicken on a baking sheet. Roast 40–45 minutes until cooked through and charred at the edges.",
      "For extra char, broil the final 5 minutes.",
      "Serve with rice and peas and fried plantain.",
    ],
  },
  {
    id: 95, name: "Rice and Peas", image: "🍚",
    time: { prep: 5, cook: 30, total: 35 }, servings: 4, difficulty: "Easy",
    equipment: ["Stove", "Medium Pot with Lid"],
    tags: ["Jamaican", "Side Dish", "Caribbean"],
    ingredients: [
      { name: "long-grain rice", amount: "300", unit: "g" },
      { name: "canned kidney beans", amount: "400", unit: "g" },
      { name: "coconut milk", amount: "200", unit: "ml" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "spring onions", amount: "2", unit: "stalks" },
      { name: "dried thyme", amount: "1", unit: "tsp" },
      { name: "allspice", amount: "1/4", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "water", amount: "400", unit: "ml" },
    ],
    steps: [
      "Drain kidney beans but keep the liquid.",
      "Combine coconut milk, water, bean liquid, smashed garlic, spring onions, thyme, allspice, and salt in a pot. Bring to a boil.",
      "Add rice and beans. Stir once.",
      "Return to a boil, then reduce to the lowest heat. Cover tightly.",
      "Cook 20 minutes without lifting the lid.",
      "Remove from heat and steam 5 more minutes. Fluff with a fork and remove the garlic and spring onions.",
    ],
  },

  // ── Nigerian ─────────────────────────────────────────────────
  {
    id: 96, name: "Jollof Rice", image: "🍚",
    time: { prep: 15, cook: 50, total: 65 }, servings: 6, difficulty: "Medium",
    equipment: ["Stove", "Large Pot with Lid", "Blender"],
    tags: ["Nigerian", "Dinner", "African", "Rice"],
    ingredients: [
      { name: "long-grain rice", amount: "400", unit: "g" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "red bell pepper", amount: "2", unit: "" },
      { name: "scotch bonnet pepper", amount: "1", unit: "or chili" },
      { name: "onion", amount: "2", unit: "large" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "chicken broth", amount: "500", unit: "ml" },
      { name: "tomato paste", amount: "3", unit: "tbsp" },
      { name: "vegetable oil", amount: "4", unit: "tbsp" },
      { name: "thyme", amount: "1", unit: "tsp dried" },
      { name: "bay leaves", amount: "2", unit: "" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Blend canned tomatoes, bell peppers, scotch bonnet, and 1 onion until smooth.",
      "Heat oil in a large pot. Fry the blended tomato mixture over high heat, stirring frequently, for 20–25 minutes until it darkens and the oil floats to the top.",
      "Add tomato paste, minced garlic, thyme, and bay leaves. Cook 5 minutes.",
      "Add sliced onion and broth. Season with salt. Bring to a boil.",
      "Wash rice, then add to the pot. Stir once.",
      "Reduce heat, cover tightly, and cook 25–30 minutes until rice absorbs all liquid.",
      "Optional: leave uncovered over high heat for the last 2 minutes to get the smoky bottom (Party Jollof).",
    ],
  },

  // ── Peruvian ─────────────────────────────────────────────────
  {
    id: 97, name: "Ceviche", image: "🐟",
    time: { prep: 20, cook: 0, total: 20 }, servings: 4, difficulty: "Medium",
    equipment: ["Knife", "Mixing Bowl"],
    tags: ["Peruvian", "Seafood", "No-Cook", "Healthy", "Latin American"],
    ingredients: [
      { name: "white fish fillets", amount: "500", unit: "g fresh, very fresh" },
      { name: "lime", amount: "8", unit: "large" },
      { name: "red onion", amount: "1", unit: "medium" },
      { name: "fresh cilantro", amount: "handful", unit: "" },
      { name: "jalapeño or ají amarillo", amount: "1", unit: "" },
      { name: "garlic", amount: "1", unit: "clove" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "corn", amount: "1", unit: "cob cooked" },
      { name: "sweet potato", amount: "1", unit: "boiled" },
    ],
    steps: [
      "Use only the freshest fish available. Cut into 2cm cubes.",
      "Thinly slice red onion and soak in cold salted water for 10 minutes to remove harshness. Drain.",
      "In a bowl, combine fish, lime juice (enough to submerge), minced garlic, sliced chili, and salt.",
      "The acid 'cooks' the fish — marinate 10 minutes for tender texture, up to 20 minutes for firmer.",
      "Fold in onion and most of the cilantro.",
      "Serve immediately in chilled bowls with corn kernels and sliced sweet potato on the side.",
    ],
  },
  {
    id: 98, name: "Lomo Saltado", image: "🥩",
    time: { prep: 15, cook: 20, total: 35 }, servings: 3, difficulty: "Medium",
    equipment: ["Stove", "Wok or Large Pan"],
    tags: ["Peruvian", "Dinner", "Stir Fry", "Latin American"],
    ingredients: [
      { name: "beef sirloin", amount: "400", unit: "g" },
      { name: "potatoes", amount: "2", unit: "large" },
      { name: "tomatoes", amount: "2", unit: "medium" },
      { name: "red onion", amount: "1", unit: "large" },
      { name: "soy sauce", amount: "3", unit: "tbsp" },
      { name: "red wine vinegar", amount: "1", unit: "tbsp" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "vegetable oil", amount: "4", unit: "tbsp" },
      { name: "fresh cilantro", amount: "handful", unit: "" },
      { name: "cooked rice", amount: "2", unit: "cups to serve" },
    ],
    steps: [
      "Cut potatoes into thick fries. Deep-fry or oven-roast until golden and crispy.",
      "Cut beef into strips and season with cumin and salt.",
      "Heat a wok until smoking. Sear beef over very high heat for 2–3 minutes. Remove.",
      "Add sliced red onion to the wok. Stir-fry 2 minutes over high heat.",
      "Add tomato wedges. Stir-fry 1 minute.",
      "Return beef. Add soy sauce, vinegar, and minced garlic. Toss vigorously over high heat.",
      "Add hot fries and cilantro. Toss once and serve immediately over rice.",
    ],
  },

  // ── Argentine ────────────────────────────────────────────────
  {
    id: 99, name: "Empanadas", image: "🥟",
    time: { prep: 45, cook: 25, total: 70 }, servings: 6, difficulty: "Medium",
    temperature: { f: 400, c: 200 },
    equipment: ["Oven", "Stove", "Pan", "Mixing Bowl", "Baking Sheet", "Oven Mitts"],
    tags: ["Argentine", "Snack", "Dinner", "Latin American"],
    ingredients: [
      { name: "flour", amount: "400", unit: "g" },
      { name: "butter", amount: "100", unit: "g cold" },
      { name: "water", amount: "120", unit: "ml cold" },
      { name: "salt", amount: "1", unit: "tsp" },
      { name: "ground beef", amount: "400", unit: "g" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "bell pepper", amount: "1", unit: "red" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "paprika", amount: "1", unit: "tsp" },
      { name: "eggs", amount: "2", unit: "hard-boiled" },
      { name: "olives", amount: "12", unit: "" },
      { name: "eggs", amount: "1", unit: "for brushing" },
    ],
    steps: [
      "Make dough: rub cold butter into flour and salt. Add cold water until dough comes together. Chill 30 minutes.",
      "Brown beef with onion, pepper, and garlic. Add cumin, paprika, and salt. Cool completely.",
      "Roll dough thin. Cut into 12cm circles.",
      "Place filling on each circle with a slice of boiled egg and an olive.",
      "Fold over and crimp or pleat edges firmly shut.",
      "Preheat oven to 400°F / 200°C. Brush with egg. Bake 20–25 minutes until golden.",
    ],
  },

  // ── Mexican (more) ───────────────────────────────────────────
  {
    id: 100, name: "Enchiladas Rojas", image: "🌮",
    time: { prep: 20, cook: 30, total: 50 }, servings: 4, difficulty: "Medium",
    temperature: { f: 375, c: 190 },
    equipment: ["Oven", "Stove", "Pan", "Baking Dish", "Oven Mitts"],
    tags: ["Mexican", "Dinner"],
    ingredients: [
      { name: "corn tortillas", amount: "12", unit: "" },
      { name: "chicken breast", amount: "400", unit: "g cooked and shredded" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "dried ancho chili", amount: "2", unit: "or chili powder 2 tbsp" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "chicken broth", amount: "200", unit: "ml" },
      { name: "cheddar cheese", amount: "150", unit: "g shredded" },
      { name: "vegetable oil", amount: "3", unit: "tbsp" },
      { name: "sour cream", amount: "to serve", unit: "" },
    ],
    steps: [
      "Blend canned tomatoes, soaked dried chilies, garlic, and cumin into a smooth sauce. Fry in oil 5 minutes. Add broth and simmer 10 minutes.",
      "Mix shredded chicken with 1/3 of the sauce and half the cheese.",
      "Preheat oven to 375°F / 190°C. Warm tortillas briefly to make pliable.",
      "Dip each tortilla in the sauce. Fill with chicken mixture and roll up.",
      "Place seam-side down in a baking dish. Pour remaining sauce over. Top with remaining cheese.",
      "Bake 20 minutes until cheese melts and edges bubble. Serve with sour cream.",
    ],
  },
  {
    id: 101, name: "Churros", image: "🍩",
    time: { prep: 10, cook: 20, total: 30 }, servings: 4, difficulty: "Medium",
    equipment: ["Stove", "Piping Bag with Star Nozzle", "Large Pot"],
    tags: ["Mexican", "Spanish", "Dessert", "Sweet", "Street Food"],
    ingredients: [
      { name: "flour", amount: "200", unit: "g" },
      { name: "water", amount: "250", unit: "ml" },
      { name: "butter", amount: "50", unit: "g" },
      { name: "salt", amount: "1/4", unit: "tsp" },
      { name: "vegetable oil", amount: "1", unit: "liter for frying" },
      { name: "sugar", amount: "100", unit: "g" },
      { name: "cinnamon", amount: "1", unit: "tsp" },
      { name: "chocolate", amount: "100", unit: "g for dipping sauce" },
      { name: "heavy cream", amount: "80", unit: "ml" },
    ],
    steps: [
      "Bring water, butter, and salt to a boil. Add flour all at once and stir vigorously until a smooth dough forms and pulls from the sides.",
      "Cool 5 minutes, then transfer to a piping bag with a large star nozzle.",
      "Heat oil to 350°F / 175°C. Pipe 15cm lengths directly into the oil, cutting with scissors.",
      "Fry 3–4 minutes, turning, until deep golden brown. Drain.",
      "Toss hot churros in cinnamon-sugar immediately.",
      "Melt chocolate with cream for dipping sauce. Serve churros warm.",
    ],
  },
  {
    id: 102, name: "Pozole Rojo", image: "🍲",
    time: { prep: 20, cook: 90, total: 110 }, servings: 6, difficulty: "Medium",
    equipment: ["Stove", "Large Pot", "Blender"],
    tags: ["Mexican", "Soup", "Dinner"],
    ingredients: [
      { name: "pork shoulder", amount: "800", unit: "g" },
      { name: "canned hominy", amount: "800", unit: "g" },
      { name: "dried guajillo chili", amount: "4", unit: "" },
      { name: "canned tomatoes", amount: "200", unit: "g" },
      { name: "onion", amount: "1", unit: "large" },
      { name: "garlic", amount: "5", unit: "cloves" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "oregano", amount: "1", unit: "tsp dried" },
      { name: "salt", amount: "1.5", unit: "tsp" },
      { name: "cabbage", amount: "1/4", unit: "shredded to serve" },
      { name: "radishes", amount: "4", unit: "sliced to serve" },
      { name: "lime", amount: "2", unit: "to serve" },
    ],
    steps: [
      "Simmer pork with half the onion, 2 garlic cloves, and salt for 60 minutes until tender. Shred and reserve broth.",
      "Toast dried chilies in a dry pan 30 seconds. Soak in boiling water 15 minutes. Blend with canned tomatoes, remaining onion, garlic, cumin, and oregano.",
      "Fry the chili sauce in a splash of oil for 5 minutes.",
      "Add shredded pork, reserved broth, and drained hominy. Simmer 20 minutes.",
      "Adjust seasoning.",
      "Serve topped with shredded cabbage, radishes, lime juice, and dried oregano.",
    ],
  },
  {
    id: 103, name: "Chiles Rellenos", image: "🫑",
    time: { prep: 20, cook: 30, total: 50 }, servings: 4, difficulty: "Hard",
    equipment: ["Stove", "Pan", "Mixing Bowl"],
    tags: ["Mexican", "Dinner", "Vegetarian"],
    ingredients: [
      { name: "poblano peppers", amount: "4", unit: "large" },
      { name: "cheddar cheese", amount: "200", unit: "g shredded" },
      { name: "eggs", amount: "3", unit: "separated" },
      { name: "flour", amount: "3", unit: "tbsp" },
      { name: "vegetable oil", amount: "1", unit: "cup for frying" },
      { name: "canned tomatoes", amount: "400", unit: "g" },
      { name: "onion", amount: "1/2", unit: "" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Char peppers directly over a flame until blackened all over. Place in a bowl, cover, steam 10 minutes. Peel skins off.",
      "Make a slit in each pepper. Remove seeds carefully. Stuff with cheese. Press shut.",
      "Make tomato sauce: blend tomatoes, onion, garlic, and cumin. Fry in oil 10 minutes.",
      "Beat egg whites to stiff peaks. Fold in yolks gently.",
      "Dust stuffed peppers in flour. Dip in egg batter.",
      "Fry in hot oil 2–3 minutes per side until golden. Serve in the tomato sauce.",
    ],
  },

  // ── Japanese (more) ──────────────────────────────────────────
  {
    id: 104, name: "Okonomiyaki", image: "🥞",
    time: { prep: 15, cook: 20, total: 35 }, servings: 2, difficulty: "Medium",
    equipment: ["Stove", "Pan", "Mixing Bowl", "Spatula"],
    tags: ["Japanese", "Lunch", "Savory Pancake"],
    ingredients: [
      { name: "cabbage", amount: "300", unit: "g finely shredded" },
      { name: "eggs", amount: "2", unit: "large" },
      { name: "flour", amount: "100", unit: "g" },
      { name: "dashi stock", amount: "100", unit: "ml" },
      { name: "bacon", amount: "4", unit: "strips" },
      { name: "spring onions", amount: "3", unit: "stalks" },
      { name: "vegetable oil", amount: "2", unit: "tbsp" },
      { name: "mayonnaise", amount: "3", unit: "tbsp" },
      { name: "okonomiyaki sauce", amount: "3", unit: "tbsp (or Worcestershire + ketchup)" },
      { name: "bonito flakes", amount: "handful", unit: "optional" },
    ],
    steps: [
      "Whisk eggs, flour, and dashi stock into a smooth batter.",
      "Fold in shredded cabbage and sliced spring onions.",
      "Heat oil in a pan over medium heat. Pour in half the batter and shape into a round pancake.",
      "Lay 2 bacon strips over the top. Cook 5 minutes until the bottom sets.",
      "Flip carefully and cook another 5 minutes until cooked through and golden.",
      "Transfer to a plate. Drizzle with mayonnaise and okonomiyaki sauce in a criss-cross pattern.",
      "Top with bonito flakes if using — they will wave in the heat.",
    ],
  },

  // ── Chinese (more) ───────────────────────────────────────────
  {
    id: 105, name: "Dan Dan Noodles", image: "🍜",
    time: { prep: 15, cook: 20, total: 35 }, servings: 2, difficulty: "Medium",
    equipment: ["Stove", "Large Pot", "Pan"],
    tags: ["Chinese", "Noodles", "Dinner", "Spicy", "Sichuan"],
    ingredients: [
      { name: "noodles", amount: "200", unit: "g wheat or spaghetti" },
      { name: "ground pork", amount: "200", unit: "g" },
      { name: "tahini", amount: "3", unit: "tbsp" },
      { name: "soy sauce", amount: "3", unit: "tbsp" },
      { name: "chili oil", amount: "2", unit: "tbsp" },
      { name: "rice vinegar", amount: "1", unit: "tbsp" },
      { name: "sesame oil", amount: "1", unit: "tbsp" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tsp" },
      { name: "Sichuan peppercorns", amount: "1/2", unit: "tsp ground" },
      { name: "spring onions", amount: "2", unit: "stalks" },
      { name: "peanuts", amount: "30", unit: "g crushed" },
    ],
    steps: [
      "Cook noodles until just done. Drain and rinse with cold water.",
      "Brown pork in a pan with a little oil, minced garlic, ginger, and 1 tbsp soy sauce. Break up finely.",
      "Make sauce: whisk tahini, remaining soy sauce, chili oil, rice vinegar, sesame oil, Sichuan pepper, and 3 tbsp noodle cooking water until smooth.",
      "Toss noodles in sauce until well coated.",
      "Divide into bowls. Top with the pork, sliced spring onions, and crushed peanuts.",
      "Add extra chili oil to taste.",
    ],
  },
];
